### ISSUE TITLE
No `lib` directory inside WeMod-8.4.1.exe

### ISSUE THREAD

**Issue by quartzar** [DaniAsh551/wemod-launcher#1]
Downloading and opening the latest WeMod installer via the link provided in instructions inside 7zip FM "Open Inside" shows no `lib` directory. Instead:

- background.gif
- RELEASES
- setupIcon.ico
- Update.exe
- WeMod-8.4.1-full.nupkg

**Comment by DaniAsh551** [comment]
Sorry, I missed one detail in the README,  the `lib` directory is actually inside the `WeMod-N.N.N-full.nupkg` file. It can be opened inside 7zip aswell. I will adjust the README.

Thanks for the catch.
