### ISSUE TITLE
[BUG]: The WeMod launcher fails with error X

### ISSUE THREAD

**Issue by Salvodif** [DaniAsh551/wemod-launcher#106]
### Describe the bug

The game doesn't start

### Steps to reproduce the behavior

Press run on the game

### Expected behavior

I expected the correct function

### Logs

chdir "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Devil May Cry 5"
ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 3657 for gameID 601150
Adding process 3658 for gameID 601150
Adding process 3659 for gameID 601150
WARNING: discarding _NET_WM_PID 1583 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 1583 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
WARNING: discarding _NET_WM_PID 1583 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
Adding process 3660 for gameID 601150
Adding process 3663 for gameID 601150
The wemod script wemod-laucher is running on version 1.486
Traceback (most recent call last):
  File "/home/blackpraedicator/Apps/wemod-launcher/wemod", line 68, in <module>
    python_venv = self_update(python_venv)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/blackpraedicator/Apps/wemod-launcher/setup.py", line 249, in self_update
    if (upd and upd.lower() == "false") or infinite > 2:
                                           ^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
Uploaded AppInterfaceStats to Steam
Removing process 3663 for gameID 601150
Removing process 3660 for gameID 601150
Removing process 3659 for gameID 601150
Removing process 3658 for gameID 601150
Removing process 3657 for gameID 601150

### System Information

                     ./o.                   User: blackpraedicator
                   ./sssso-                 Hostname: Glamdring
                 `:osssssss+-               OS: EndeavourOS  x86_64
               `:+sssssssssso/.             Kernel: Linux 6.9.8-arch1-1
             `-/ossssssssssssso/.           Uptime: 3 hours, 22 mins
           `-/+sssssssssssssssso+:`         Load Average: 2,87, 2,92, 2,43
         `-:/+sssssssssssssssssso+/.        Processes: 494
       `.://osssssssssssssssssssso++-       Window Manager: KWin (Wayland)
      .://+ssssssssssssssssssssssso++:      Desktop Environment: KDE Plasma 6.1.2
    .:///ossssssssssssssssssssssssso++:     Shell: /usr/bin/fish
  `:////ssssssssssssssssssssssssssso+++.    Terminal: konsole 24.5.2 ██ ██ ██ ██ ██ ██ ██ ██
`-////+ssssssssssssssssssssssssssso++++-    Packages: 1786
 `..-+oosssssssssssssssssssssssso+++++/`    Temperature: 100,0°C
   ./++++++++++++++++++++++++++++++/:.      CPU: 20 x 13th Gen Intel(R) Core(TM) i5-13600K
  `:::::::::::::::::::::::::------``        GPU: GeForce RTX 3070 Ti
                                            RAM: 8,83 GiB / 31,09 GiB (28%)
                                            Disk: 235,12 GiB / 906,17 GiB (26%) - ext4
                                            LAN IP: 192.168.10.85 fe80::baa0:687e:2f:3863
                                            WAN IP: 31.195.2.58 (Rome, IT)

**Comment by marvin1099** [comment]
yes that was a update i messed up its fixed already, 
but since i broke the start lines the auto updater wont trigger so run:  

    cd /home/$USER/wemod-launcher
    git reset --hard origin
    git pull
    sudo chmod -R ug+x .

**Comment by Salvodif** [comment]
I just changed game (Hades) and doesn't starts anymore nor game nor wemod

> x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.555.58.02 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32:/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/panorama:/app/utils/steamtinkerlaunch/lib:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/nvidia-555-58-02/lib:/app/lib/ffmpeg/.:/app/lib32/ffmpeg/.:/app/lib32:/app/lib/i386-linux-gnu:/lib64:/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/GL/nvidia-555-58-02/lib:/usr/lib/x86_64-linux-gnu", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
> F: Not sharing "/usr/lib/git-core" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/bin/git" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/share/git" with sandbox: Path "/usr" is reserved by Flatpak
> wine: using kernel write watches, use_kernel_writewatch 1.
> fsync: up and running.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> chdir "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Hades/x64/"
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2066 for gameID 1145360
> WARNING: discarding _NET_WM_PID 1569 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
> Adding process 2067 for gameID 1145360
> Adding process 2068 for gameID 1145360
> Adding process 2069 for gameID 1145360
> Adding process 2072 for gameID 1145360
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: symbol lookup error: /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2073 for gameID 1145360
> Adding process 2074 for gameID 1145360
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2076 for gameID 1145360
> Adding process 2077 for gameID 1145360
> Adding process 2078 for gameID 1145360
> Adding process 2080 for gameID 1145360
> 

[wemod.log](https://github.com/user-attachments/files/16235168/wemod.log)

**Comment by Salvodif** [comment]
> [I] ^^>>> flatpak run com.valvesoftware.Steam                                                                                                                             12:13:05 
> F: Not sharing "/usr/lib/git-core" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/bin/git" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/share/git" with sandbox: Path "/usr" is reserved by Flatpak
> INFO:root:https://github.com/flathub/com.valvesoftware.Steam/wiki
> INFO:root:Will set XDG dirs prefix to /home/blackpraedicator/.var/app/com.valvesoftware.Steam
> DEBUG:root:Checking input devices permissions
> WARNING:root:Missing permissions for input devices
> INFO:root:Overriding TZ to Europe/Rome
> steam.sh[2]: Running Steam on org.freedesktop.platform 23.08 64-bit
> steam.sh[2]: STEAM_RUNTIME is enabled automatically
> setup.sh[75]: Steam runtime environment up-to-date!
> steam.sh[2]: Steam client's requirements are satisfied
> [2024-07-16 12:13:09] Startup - updater built Jun 20 2024 17:13:49
> [2024-07-16 12:13:09] Startup - Steam Client launched with: '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam' '-srt-logger-opened' '-no-cef-sandbox'
> 07/16 12:13:09 minidumps folder is set to /tmp/dumps
> 07/16 12:13:09 Init: Installing breakpad exception handler for appid(steam)/version(1718904662)/tid(135)
> [2024-07-16 12:13:09] Loading cached metrics from disk (/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/package/steam_client_metrics.bin)
> [2024-07-16 12:13:09] Using the following download hosts for Public, Realm steamglobal
> [2024-07-16 12:13:09] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
> [2024-07-16 12:13:09] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
> [2024-07-16 12:13:09] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
> [2024-07-16 12:13:09] Verifying installation...
> [2024-07-16 12:13:09] Verification complete
> UpdateUI: skip show logo
> Steam logging initialized: directory: /home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/logs
> 
> XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe1ea38f0
> XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe1ea21c0
> CAppInfoCacheReadFromDiskThread took 17 milliseconds to initialize
> Steam Runtime Launch Service: starting steam-runtime-launcher-service
> Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 244
> bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> BRefreshApplicationsInLibrary 1: 0ms
> BuildCompleteAppOverviewChange: 153 apps
> RegisterForAppOverview 1: 3ms
> RegisterForAppOverview 2: 3ms
> x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.555.58.02 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32:/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/panorama:/app/utils/steamtinkerlaunch/lib:/app/lib/i386-linux-gnu/GL/default/lib:/app/lib/i386-linux-gnu/GL/nvidia-555-58-02/lib:/app/lib/ffmpeg/.:/app/lib32/ffmpeg/.:/app/lib32:/app/lib/i386-linux-gnu:/lib64:/app/lib:/usr/lib/x86_64-linux-gnu/GL/default/lib:/usr/lib/x86_64-linux-gnu/GL/nvidia-555-58-02/lib:/usr/lib/x86_64-linux-gnu", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
> F: Not sharing "/usr/lib/git-core" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/bin/git" with sandbox: Path "/usr" is reserved by Flatpak
> F: Not sharing "/usr/share/git" with sandbox: Path "/usr" is reserved by Flatpak
> wine: using kernel write watches, use_kernel_writewatch 1.
> fsync: up and running.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> wine: using kernel write watches, use_kernel_writewatch 1.
> chdir "/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Hades/x64/"
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2064 for gameID 1145360
> Adding process 2065 for gameID 1145360
> Adding process 2066 for gameID 1145360
> WARNING: discarding _NET_WM_PID 1581 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
> WARNING: discarding _NET_WM_PID 1581 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
> WARNING: discarding _NET_WM_PID 1581 as invalid for X11 window - use specialized XCB_X11_TO_PID function!
> Adding process 2067 for gameID 1145360
> Adding process 2070 for gameID 1145360
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: symbol lookup error: /app/utils/steamtinkerlaunch/libexec/git-core/git-remote-https: undefined symbol: curl_global_sslset
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2071 for gameID 1145360
> Adding process 2072 for gameID 1145360
> ERROR: ld.so: object '/home/blackpraedicator/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
> Adding process 2074 for gameID 1145360
> Adding process 2075 for gameID 1145360
> Adding process 2076 for gameID 1145360
> Adding process 2078 for gameID 1145360
> 

[wemod.log](https://github.com/user-attachments/files/16247108/wemod.log)
