### ISSUE TITLE
[BUG]: Opening wemod not functioning correctly

### ISSUE THREAD

**Issue by Shinikoja** [DaniAsh551/wemod-launcher#110]
### Describe the bug

Opening the app gives me the error "game closed too early" and trying to open the game with wemod it gives the warning "running 32x" and refuses to allow me to play

### Steps to reproduce the behavior

Launch game
wemod opens, doesn't let me start game because "32x version"
Game closes too early

### Expected behavior

To be able to open the game and use modifications

### Logs

[wemod.log](https://github.com/user-attachments/files/16463587/wemod.log)

### System Information

OS: Debian 12
Wine: GE-Proton9-11

**Comment by marvin1099** [comment]
Have you tryed to run the game without wemod,
also have you tryed a other game.
Maby you could check if it works with GE-Proton9-1.

Im dont know what the Problem is right now.

Please send over the "running 32x" error if you get it, but if its just a error of runtime32.exe then it can be ignored.

**Comment by marvin1099** [comment]
i assume you problem was solved,
if not say so and i will reopen this.
