### ISSUE TITLE
[BUG]: Package 'FreeSimpleGUI' is missing

### ISSUE THREAD

**Issue by ArkNill** [DaniAsh551/wemod-launcher#113]
### Describe the bug

I was trying install wemod in steamdeck

### Steps to reproduce the behavior

1. Product reset
2. enable developer mode
3. download raft
4. change into desktop mode
5. use discover to download protonup-qt and protontricks
6. use protonup-qt download ge-proton9-1
7. restart steamdeck
8. git clone https://github.com/DaniAsh551/wemod-launcher.git
9. sudo chmod -R ug+x /home/deck/wemod-launcher
10. set /home/deck/wemod-launcher/wemod %command%
11. set compatibility ge-proton9-1
12. start game
13. choose build, winetricks
14. error occur while proccessing

### Expected behavior

When I selected 'download', it was downloaded, but an error window appeared saying that Net Framework 48 had already been installed. A game window appeared along with the wemode login page, but as soon as I finished the game, the login page closed as well.

### Logs

[wemod.log](https://github.com/user-attachments/files/16615877/wemod.log)

### System Information

steam os version : 3.5.19
kernel version 6.1.52 -valve16-1-neptune-61

### Additional context

Hello,

I recently purchased a Steam Deck and, thanks to your excellent work, I discovered through YouTube that WeMod can also be used on the Steam Deck. I'm currently trying to apply it, but unfortunately, I'm encountering some difficulties.

I followed the instructions based on the YouTube video you posted. I also noticed a response to an inquiry by 'calvyb,' where it was mentioned that the issue was due to the absence of the Python virtual environment (venv). Since I’m using SteamOS on a Steam Deck, I’m wondering if this issue might also be relevant to my setup.

Additionally, in the tutorial video, GE-Proton 9-6 was used for the demonstration. I have seen comments where users mentioned that GE-Proton 9-7 is stable, and I also read in another entry on the issues tab that GE-Proton 9-1 was found to be stable.

Could you please advise on which version of Proton is considered the most stable for use on the Steam Deck?

Thank you very much for your assistance.

**Comment by marvin1099** [comment]
It really doesn't matter what GE-Proton9 version  you use since so far any GE-Proton9 version has worked with the wemod-launcher.
Your venv creation works fine two that's not the issue.
The issue is with the old code that builds the wemod laucher,
sadly as mentioned on lots of issues building is broken for many systems, i recommend using download.
Sadly even though i am the main contribute-ter right now,
I don't know how to fix this since the code for building is old and not made by me.

**Comment by marvin1099** [comment]
> It really doesn't matter what GE-Proton9 version you use since so far any GE-Proton9 version has worked with the wemod-launcher. Your venv creation works fine two that's not the issue. The issue is with the old code that builds the wemod laucher, sadly as mentioned on lots of issues building is broken for many systems, i recommend using download. Sadly even though i am the main contribute-ter right now, I don't know how to fix this since the code for building is old and not made by me.

Also FreeSimpleGUI gets downloaded just file
and try to delete the game prefix so download can work.
For that click the option in the troubleshooter,
or follow the Meta Step in Step 3 right here:
https://github.com/DaniAsh551/wemod-launcher/wiki/Full-guide#step-3-installing-wemod-launcher

**Comment by marvin1099** [comment]
I assume this was solved if not say so and i will reopen this.
