### ISSUE TITLE
[BUG]: The WeMod freezes on launch

### ISSUE THREAD

**Issue by calvyb** [DaniAsh551/wemod-launcher#115]
### Describe the bug

Installed the launcher followed the instructions. to the point where i press play on a game it opens a black box though it does say game closed to fast, but then pops up wemod and my game. however after 2-3 seconds the we mod window freezes.

### Steps to reproduce the behavior

Installed python-virtualenv python-pip tk proton tricks and proton up.
cloned wemod from git hub
set steam preferences to launch with proton and /home/me/we-mod-launcher/wemod-launcher %command%
press play
on option to dopwnload or build click download.
couple of errors pop up about .net framework.

click play game black box pops up we mod pops up batwarning prompt pops up, we mod freezes.

### Expected behavior

managed to have it working on another computer running mint but not sure why its freezing on this one. Arch

### Logs

[wemod.log](https://github.com/user-attachments/files/16645462/wemod.log)

### System Information

Operating System: Arch Linux 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.6.46-1-lts (64-bit)
Graphics Platform: Wayland
Processors: 16 × 13th Gen Intel® Core™ i5-13400
Memory: 31.1 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4070/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D40
System Version: 2.0

**Comment by marvin1099** [comment]
Probably the same as #108, go over there i will try to find the issue.
