### ISSUE TITLE
[BUG]: WeMod shorcuts under SteamOS gaming mode freeze the device

### ISSUE THREAD

**Issue by believeinyuna** [DaniAsh551/wemod-launcher#119]
### Describe the bug

using the latest version of wemod-launcher, got everything working on game mode (doesn’t work on desktop mode), able to switch between wemod and the game. i changed the hotkey of a cheat to the button 8, and switched back to the game, enabled steam deck keyboard, pressed 8, and everything freezes with an audio glitch, sometimes it black screens and sometimes it just freezes the game, i have to press the power button for 3 seconds to turn it off. the game is fields of mistria, using ge-proton 9.11 (latest). 

### Steps to reproduce the behavior

1. use wemod-launcher with fields of mistria in game mode 
2. set a custom keybind to enable chest that steam deck keyboard can do (like a number)
3. switch to game and open the steam deck keyboard 
4. press the button you set. you will hear wemod activating it 
5. the game will freeze and crash

### Expected behavior

it doesn’t crash

### Logs

n/a

### System Information

steamOS
GE-proton 9.11

**Comment by believeinyuna** [comment]
i have tried setting the hotkeys to something i can use in wemod (in this case r5 on the deck which comes up as ‘left’ in wemod) and enabled it. the mod enables and i get a privacy agreement pop up on wemod. after a few seconds it freezes. enabling this agreement, or switching back to fields of mistria, doesn’t change anything, it always freezes on enable.

**Comment by marvin1099** [comment]
This is a wemod issue (it may also be a issue of steam os), not a issue by wemod-launcher.
All you can try is to activate the cheat by clicking on it instead of using the hotkey,
you can also try to make it work in desktop mode, there hotkeys have worked for other users in the past.
If you want help setting that up, then i can probably help.
You can also just check out the [wemod-launcher wiki](https://github.com/DaniAsh551/wemod-launcher/wiki) it has guides you can follow.
For a simple setup there is the [wiki quick guide](https://github.com/DaniAsh551/wemod-launcher/wiki/Quick-Guide) and
there also is a very [detailed guide here](https://github.com/DaniAsh551/wemod-launcher/wiki/Full-guide)

**Comment by believeinyuna** [comment]
unfortunately i cannot access wemod in desktop mode (i can’t make wemod be on top of the game window, or tab out of the game, or switch windows) and i don’t have wemod pro to be able to click on the options themselves so i assume i’m out of options :(

**Comment by marvin1099** [comment]
Why cant you tab out exactly?
It tabbing out may work better if you use borderless fullscreen mode.
Usually you can tab out using `alt + tab` or you should be able to press the meta key (windows key) 
to open the application menu, from there you can use `alt + tab`.
Also in if you still want gaming mode you can switch between all opened windows / progamms using the steam button if you have developer mode enabled.

**Comment by believeinyuna** [comment]
the game doesn’t let you switch between full screen, borderless or windowed. it has no options like that. i’ve tried alt tab and it doesn’t do anything. in fact when the game launches nothing works, just the in game buttons, all shortcuts and commands stop working. i assume it’s just something to do with how fields of mistria is. 

and that’s what i was doing, i had developer mode on in game mode and that’s how i switched to wemod and back. but again that caused my deck to crash when enabling any trainer options.

**Comment by marvin1099** [comment]
If the game has no borderless fullscreen mode (this is of couse only usefull for destkop mode), you can use windowed mode and then use the kde desktop shorcut to make it a borderless window.

**Comment by marvin1099** [comment]
> the game doesn’t let you switch between full screen, borderless or windowed. it has no options like that. i’ve tried alt tab and it doesn’t do anything. in fact when the game launches nothing works, just the in game buttons, all shortcuts and commands stop working. i assume it’s just something to do with how fields of mistria is.
> 
> and that’s what i was doing, i had developer mode on in game mode and that’s how i switched to wemod and back. but again that caused my deck to crash when enabling any trainer options.

So it crashed if you clicked on the option then?

**Comment by marvin1099** [comment]
> If the game has no borderless fullscreen mode (this is of couse only usefull for destkop mode), you can use windowed mode and then use the kde desktop shorcut to make it a borderless window.

Well dose mistria have a window mode?

**Comment by believeinyuna** [comment]
i can’t test clicking on it, as i said before i don’t have pro. i can only do the hotkeys. 

no, i said before, no option for windowed. 

> the game doesn’t let you switch between full screen, borderless or windowed. it has no options like that. i’ve tried alt tab and it doesn’t do anything. in fact when the game launches nothing works, just the in game buttons, all shortcuts and commands stop working. i assume it’s just something to do with how fields of mistria is.

**Comment by marvin1099** [comment]
Thats what confused me, you can click to enable mods just fine in wemod without having pro, 
you need pro to use the mobile app, then you can do it on a other device

**Comment by believeinyuna** [comment]
nope. when i try to click them it says it requires pro. you can only use the hotkeys. i looked into it, and it is a paid for feature to click on them.

**Comment by believeinyuna** [comment]
https://community.wemod.com/t/every-cheat-for-every-game-is-for-pro/78015

discussion about it on wemods own forums.

**Comment by marvin1099** [comment]
would you upload a screenshot of the mods section and also you clicking on the mod?

**Comment by marvin1099** [comment]
for me it looks like this:
![Screenshot_20240824_235935](https://github.com/user-attachments/assets/e8ab7bd9-8d46-4037-9f65-ceb960b94ee5)
then i clicked on it
![Screenshot_20240824_235949](https://github.com/user-attachments/assets/e3b44a34-01c9-4dad-a672-e6d81d863fbe)

**Comment by marvin1099** [comment]
I see i think i have a old version then???
I can send you my files if you like to try them.

**Comment by believeinyuna** [comment]
![IMG_6089](https://github.com/user-attachments/assets/400200ca-762f-4d80-8236-3e15e42fa262)
i can’t send my own screenshot. i got this from google. it looks like this when you try to click. 

when i use git pull it says i have the latest version. i installed it only today, so i doubt wemod-launcher gave me an old version of wemod?

**Comment by marvin1099** [comment]
Got it so some stuff can be used with mouse, 
in your screenshot Unlimited potions are free.
Have you tried using a external keyboard?
That may work.

**Comment by marvin1099** [comment]
Here are also some other ways you may be able to tab out in destop mode:
Use Alt + Space to open KRunner.
Set a shortcut for minimizing all windows like Ctrl + Alt + D and press it.
Set a shortcut for switching to another desktop, like Ctrl + Alt + → or Ctrl + Alt + ←, and press it to move to a different desktop.
Set a shortcut for focusing the next or previous window, like Meta + Tab, and use it to change focus.
Use Ctrl + Alt + F4 to switch to a TTY, then return with Ctrl + Alt + F2.
Press Ctrl + Esc to open System Activity and select a different window.

**Comment by believeinyuna** [comment]
i don’t have a physical keyboard so i can’t try these, sorry.

**Comment by marvin1099** [comment]
> Here are also some other ways you may be able to tab out in destop mode: Use Alt + Space to open KRunner. Set a shortcut for minimizing all windows like Ctrl + Alt + D and press it. Set a shortcut for switching to another desktop, like Ctrl + Alt + → or Ctrl + Alt + ←, and press it to move to a different desktop. Set a shortcut for focusing the next or previous window, like Meta + Tab, and use it to change focus. Use Ctrl + Alt + F4 to switch to a TTY, then return with Ctrl + Alt + F2. Press Ctrl + Esc to open System Activity and select a different window.

You can of course change the shortcuts to something a steamdeck can use (you and also try to change the shortcut for regular tabbing out).

**Comment by believeinyuna** [comment]
yes i tried to do it through steam deck controller settings and changing keybinds to do different combos. they work fine until i open the game, then they stop working.

**Comment by marvin1099** [comment]
What exactly is the game name, i only game found on steam was `Fields of Mistria` and that game has a window mode, you dont mean that one do you?

**Comment by marvin1099** [comment]
There is a way to make any game run in window mode you can use `gamescope` to run the game in a window.
You can set the steam command to (install gamescope for that of course):
```
/home/$USER/wemod-launcher/wemod gamescope -w 1920 -h 1080 --fullscreen -r 60 -- %command%
```
where you have full control over the game-window, 
by adding --fullscreen you enable fullscreen (so you may need to remove it actually)
-w and -h set the window size
-r sets the framerate
you can remove or add these as you need.

**Comment by marvin1099** [comment]
I assume this has solved the issue, please say if not, for now i will close this issue.
