### ISSUE TITLE
WeMod Login screen unresponsive

### ISSUE THREAD

**Issue by PlasmaPangolin** [DaniAsh551/wemod-launcher#12]
In steam deck desktop mode, I am able to install and run the launcher up to Step 3 and the "Hello from WeMod Launcher" window, but the 'Press any key to continue' terminal I can only bypass by holding the steam button and right trigger to use the menu to to paste text in and the wem9d launcher window is otherwise unresponsive to steam deck controls.  

That workaround gets me to the WeMod login screen, which is also unresponsive to controls except for holding the Steam button while using the right track pad which moves the cursor and left trigger to click.

I don't have a Bluetooth keyboard, so I am pretty much dead in the water at step 4 of the setup instructions. Steam keyboard doesn't come up, paste menu doesn't come up, there is literally no way to enter information to log in or create an account.

**Comment by DaniAsh551** [comment]
This is a known issue currently, my guess is that the SD soft keyboard is not able to interact with xwayland windows.

For now, we really don't have a fix until either WeMod decides to release a Linux/SD native version of WeMod or until wine/Proton gets first class Wayland support (if my previous guess is correct)

The workaround is that you would do the first-time launch in desktop mode or with a physical keyboard attached.
