### ISSUE TITLE
[BUG]: The WeMod launcher won`t continue after x

### ISSUE THREAD

**Issue by yeris88** [DaniAsh551/wemod-launcher#120]
### Describe the problem

When i click on play on wemod i get the error saying that the mods are made for 32bit versions of the game and i am on 64bit version

### Steps that will result in the problem

Click play

### Expected results

The game to launch

### Logs

WeModLog path was not given or invalid using path 'wemod.log'
If you don't want to generate a logfile use WEMOD_LOG='' or set the config to WeModLog=''
Adding script name to config
Adding script version to config
The script wemod-laucher is running on version 1.498
Package 'FreeSimpleGUI' is missing
Pip error appered:
	b''
	b"ERROR: ld.so: object '/home/yeris/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.\n/bin/sh: 1: pip: not found\n"
Pip error appered:
	b''
	b"ERROR: ld.so: object '/home/yeris/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.\nERROR: ld.so: object '/home/yeris/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.\n/usr/bin/python3: No module named pip\n"
Pip not found. Downloading...
Externally managed environment detected.
Virtual environment created successfully.
Pip finished successfully
No updates available
Re-running script within virtual environment 
or to update or to run outside of flatpak with the command:
	['/home/yeris/wemod-launcher/wemod_venv/bin/python', '/home/yeris/wemod-launcher/wemod', '/home/yeris/.steam/debian-installation/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2229850', '--', '/home/yeris/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper', '--', '/home/yeris/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/yeris/.steam/debian-installation/compatibilitytools.d/GE-Proton9-11/proton', 'waitforexitandrun', '/home/yeris/.steam/debian-installation/steamapps/common/Command & Conquer Red Alert II/Ra2.exe']

The rerun nr 1 was started
The script wemod-laucher is running on version 1.498
No updates available
The normal args list is 12 long and the full contents are:
	['/home/yeris/.steam/debian-installation/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2229850', '--', '/home/yeris/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper', '--', '/home/yeris/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/yeris/.steam/debian-installation/compatibilitytools.d/GE-Proton9-11/proton', 'waitforexitandrun', '/home/yeris/.steam/debian-installation/steamapps/common/Command & Conquer Red Alert II/Ra2.exe']
Looking for init file '/home/yeris/.steam/debian-installation/steamapps/compatdata/2229850/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/yeris/.steam/debian-installation/steamapps/compatdata' with proton version '9.11'
No compatible Proton version found in the compatibility folder.
No versions to copy available
Looking once more for the init file
Init file not found! Attempting to prepare the WINEPREFIX
Using wine from Proton at path: '/home/yeris/.steam/debian-installation/compatibilitytools.d/GE-Proton9-11/files/bin'
Cache dir not found. Creating...
Cached file not found: '/home/yeris/wemod-launcher/.cache/wemod_prefix9.1.zip'
Unpacking prefix file /home/yeris/wemod-launcher/.cache/wemod_prefix9.1.zip into /home/yeris/.steam/debian-installation/steamapps/compatdata/2229850
Syncing wemod data from '/home/yeris/.steam/debian-installation/steamapps/compatdata/2229850/pfx/drive_c/users/steamuser/AppData/Roaming/WeMod' to laucher dir '/home/yeris/wemod-launcher/wemod_data'
Linked wemod data to gameprefix
Winetricks not found...
Downloading latest winetricks...
Finished prefix download and unpacking
Syncing wemod data from '/home/yeris/.steam/debian-installation/steamapps/compatdata/2229850/pfx/drive_c/users/steamuser/AppData/Roaming/WeMod' to laucher dir '/home/yeris/wemod-launcher/wemod_data'
D:/home/yeris/.steam/debian-installation/steamapps/common/Command & Conquer Red Alert II
R:['/home/yeris/.steam/debian-installation/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2229850', '--', '/home/yeris/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper', '--', '/home/yeris/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--']
P:/home/yeris/.steam/debian-installation/compatibilitytools.d/GE-Proton9-11/proton
V:['waitforexitandrun']
B:['start', 'Z:\\\\home\\\\yeris\\\\wemod-launcher\\\\wemod.bat']
G:Ra2.exe
L:[]
Creating a game time tracking file, the file is:
	/home/yeris/wemod-launcher/.cache/early.tmp
Executing:
	['/home/yeris/.steam/debian-installation/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2229850', '--', '/home/yeris/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper', '--', '/home/yeris/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/yeris/.steam/debian-installation/compatibilitytools.d/GE-Proton9-11/proton', 'waitforexitandrun', 'start', 'Z:\\\\home\\\\yeris\\\\wemod-launcher\\\\wemod.bat', 'Ra2.exe']
Running in regular mode
Communicating with the process
The game ran long enough, wemod is now allowed to close on game exit, therefore early game close detetion is finished

### System Information

OS: Debian Trixi
GE-Proton9-11

**Comment by marvin1099** [comment]
Not something i can help you with, that is a wemod issue (might even be on purpose).
All i can say is if you game supports 64bit make shure you use the 64bit version.
Usually this should be done automatically if possible.
But it it is not done automatically you can set the windows (wine) version of the game to 64 bit.
To do that find your prefix folder.
In steam your prefix folders are at `/home/$USER/.steam/steam/steamapps/compatdata/`.
The correct prefix folder is the one that has the GameID your game has.
To check the GameID of a Game use the app `protontricks`, the GameID is listed there.
Once you have the prefix folder, add a `pfx` at the end (for steam) and run:
```
rm -rf $PREFIX-FOLDER-HERE
WINEARCH=win64 WINEPREFIX="$PREFIX-FOLDER-HERE" winecfg
```
The $PREFIX-FOLDER-HERE may look like this `/home/$USER/.steam/steam/steamapps/compatdata/1440670/pfx/`
Replace the $PREFIX-FOLDER-HERE with the path to the wine prefix.
Finally click OK in the opened window.
Now when running the game in steam i will ask you to re-download wemod.
And then it should work, but its also possible your game has not 64bit version.
In that case wemod may be wrong and you will have to reach out to the wemod community.
