### ISSUE TITLE
Game tries and failes to launch

### ISSUE THREAD

**Issue by ExtraDryMartini** [DaniAsh551/wemod-launcher#122]
### Describe the problem

Followed the full guide.  Trying to launch the game to open Wemod causes Steam to almost get it launched before ending the process and returning to Steam library.  It's probably user error but I don't know enough about code to figure out why.

### Steps that will result in the problem

Try to launch game(Nioh 2) in Steam Library.

### Expected results

Wemod to launch.

### Logs

Terminal info after launching Steam via terminal:
ine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
chdir "/home/luke/.steam/debian-installation/steamapps/common/Nioh2"
ERROR: ld.so: object '/home/luke/.steam/debian-installation/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: 1: /home/Luke/wemod-launcher/wemod: not found
Uploaded AppInterfaceStats to Steam
Adding process 110841 for gameID 1325200
Removing process 110841 for gameID 1325200

### System Information

Mint 22 Cinnamon 6.2.9  GE Proton9-13 Steam installed as system package.

**Comment by ExtraDryMartini** [comment]
Changed the $user in the launch features to lowercase, now I have this error:
[wemod.log](https://github.com/user-attachments/files/17009498/wemod.log)

**Comment by ExtraDryMartini** [comment]
Okay, figured out how to install FreeSimpleGUI,  now launching the game in Steam generates this error.  
The script wemod-laucher is running on version 1.498
No updates available
The normal args list is 12 long and the full contents are:
	['/home/luke/.steam/debian-installation/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=1325200', '--', '/home/luke/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper', '--', '/home/luke/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/luke/.steam/debian-installation/compatibilitytools.d/GE-Proton9-13/proton', 'waitforexitandrun', '/home/luke/.steam/debian-installation/steamapps/common/Nioh2/nioh2.exe']
ERR:
[Errno 25] Inappropriate ioctl for device

Don't have a clue how to proceed now.

**Comment by marvin1099** [comment]
this was fixed today in #125 rerun,
it should auto update.

**Comment by marvin1099** [comment]
reopen if any other problems appear
