### ISSUE TITLE
[BUG]: The WeMod launcher won’t launch. 

### ISSUE THREAD

**Issue by ndzrh** [DaniAsh551/wemod-launcher#123]
### Describe the problem

I followed all the guide manage to get the game launch and everything but wemod just pop up BAT warning saying game close too fast. 

### Steps that will result in the problem

Followed all the guide. Wemod launcher does popup but then that popup from my picture comes up everytime I launch the game. 

### Expected results

Wemod launcher to launch

### Logs

No log

### Screenshots

![IMG_7752](https://github.com/user-attachments/assets/5644936f-411d-459d-8b36-48203534b989)

### System Information

Steam deck

**Comment by marvin1099** [comment]
This is a warning, this means the game was not found, 
this just means wemod wont close with the game automatically.
This game probably starts as a separate fork,
then i can be tracked by the launcher.

All you need to do is click "yes" on the fist warning to wait longer, 
and then minimize the warning from the image.
Wemod should start anyway.
And when your done playing you can click "ok" on the warning to close wemod.

**Comment by marvin1099** [comment]
I assume this works for you, if not say so then i will reopen this.
