### ISSUE TITLE
Dotnet48 won’t download

### ISSUE THREAD

**Issue by Phanny9** [DaniAsh551/wemod-launcher#124]
### Describe the problem

After following the steps on WeMod discord it doesn’t download dotnet 48. It stops at 0% 0/0.

### Steps that will result in the problem

Followed all steps in the guide.

### Expected results

The guide says 10 mins but left it all night and still no movement or explanation. 

### Logs

WEMOD_LOG=/home/deck/wemod-launcher/wemod.log /home/deck/wemod-launcher/wemod %command%

### System Information

![image](https://github.com/user-attachments/assets/b64b42c1-c1c3-454c-9a49-4017c9610944)

### Additional context

I am fairly new to Linux and steam deck

**Comment by marvin1099** [comment]
As mentioned in may issues sadly building is not working for many devices.
Just use the download option like it says in the README.
just scroll down [here](https://github.com/DaniAsh551/wemod-launcher) to get to the README.

**Comment by marvin1099** [comment]
I assume you have done so and it has worked, if not so say so and i will reopen this.

**Comment by Phanny9** [comment]
Not completed yet, Please allow me a little time to figure it out Kind regardsLiOn 23 Sep 2024, at 13:40, Marvin1099 ***@***.***> wrote:﻿
I assume you have done so and it has worked, if not so say so and i will reopen this.

**Comment by marvin1099** [comment]
Got it, i will reopen for now.
Report if you have more questions ore solved the issue.
Here is the written tutorial on [how to do it](https://github.com/DaniAsh551/wemod-launcher),
And there is also this [video tutorial](https://youtu.be/5UlVCZvIl1E)
but i think i used build in that one, but download works on more systems, so use that as mentioned.

**Comment by marvin1099** [comment]
How is it going?
Did you make it work?

**Comment by marvin1099** [comment]
I assume you did make it work.
If not you can say so but i have not heard from you in a while 
and I want to keep the issues organized.
So will close this for now.
I will reopen if you say that these steps have not worked.
You can still leave comments after this is closed, its really just for organization.
