### ISSUE TITLE
[BUG]: The WeMod launcher won`t launch

### ISSUE THREAD

**Issue by Unrulymaster** [DaniAsh551/wemod-launcher#125]
### Describe the problem

launch a game with /home/$USER/wemod-launcher/wemod %command% using GE-Proton9-1 and it just says "Error occored, open the log?" clicking no closes the window and stops the game from executing clicking yes displays the log included.

### Steps that will result in the problem

running games with wemod installed and the launch command: /home/$USER/wemod-launcher/wemod %command%

### Expected results

wemod should launch alongside game 

### Logs

The script wemod-laucher is running on version 1.498
Package 'FreeSimpleGUI' is missing
Externally managed environment detected.
Virtual environment created successfully.
Pip finished successfully
No updates available
Re-running script within virtual environment 
or to update or to run outside of flatpak with the command:
	['/home/liam/wemod-launcher/wemod_venv/bin/python', '/home/liam/wemod-launcher/wemod', '/home/liam/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=275850', '--', '/home/liam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/mnt/Linux games/steam library/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/liam/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', "/mnt/More linux games/SteamLibrary/steamapps/common/No Man's Sky/Binaries/NMS.exe"]

The rerun nr 1 was started
The script wemod-laucher is running on version 1.498
No updates available
The normal args list is 12 long and the full contents are:
	['/home/liam/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=275850', '--', '/home/liam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/mnt/Linux games/steam library/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/liam/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', "/mnt/More linux games/SteamLibrary/steamapps/common/No Man's Sky/Binaries/NMS.exe"]
ERR:
[Errno 25] Inappropriate ioctl for device

The script wemod-laucher is running on version 1.498
No updates available
The normal args list is 12 long and the full contents are:
	['/home/liam/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=275850', '--', '/home/liam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/mnt/Linux games/steam library/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/liam/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', "/mnt/More linux games/SteamLibrary/steamapps/common/No Man's Sky/Binaries/NMS.exe"]
ERR:
[Errno 25] Inappropriate ioctl for device

### System Information

linux mint 22 wilma using proton GE 9.1 

### Additional context

i have used other proton versions both GE and normal.

**Comment by marvin1099** [comment]
This seems to be a very rare occurrence.
Go and make shure you run python 3,
for that run:
``` 
python --version
```
[Next download this replacement test file](https://github.com/user-attachments/files/17076168/wemod.zip) and unzip it.  
Place the wemod file inside the wemod.zip into the wemod laucher folder.
If you have followed the guide its at `/home/$USER/wemod-launcher`.
then run this command in bash:
```
CONFIG_FILE="/home/$USER/wemod-launcher/wemod.conf"; touch "$CONFIG_FILE"; grep -q "^\[Settings\]" "$CONFIG_FILE" || echo -e "\n[Settings]" >> "$CONFIG_FILE"; grep -q "^SelfUpdate =" "$CONFIG_FILE" && sed -i 's/^SelfUpdate = .*/SelfUpdate = false/' "$CONFIG_FILE" || sed -i '/^\[Settings\]/a SelfUpdate = false' "$CONFIG_FILE"
```
This will disable auto-updates for the launcher so you can use the new test file i have uploaded in this conversation.
After that run the game with the wemod launcher and send the contents of the updated wemod.log file.

**Comment by Unrulymaster** [comment]
This is what the log says: The script wemod-laucher is running on version 1.498
Self update skipped
The normal args list is 12 long and the full contents are:
	['/home/liam/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=275850', '--', '/home/liam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/mnt/Linux games/steam library/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/liam/.local/share/Steam/compatibilitytools.d/GE-Proton9-13/proton', 'waitforexitandrun', "/mnt/More linux games/SteamLibrary/steamapps/common/No Man's Sky/Binaries/NMS.exe"]
GetGame
Options
Init
ERR:
[Errno 25] Inappropriate ioctl for device

**Comment by marvin1099** [comment]
This issue seems very obscure,  
[i can yet find the issue jet use this here.](https://github.com/user-attachments/files/17077923/wemod.zip)  
replace the 2 files in the launcher folder and rerun the game.
After send over the new wemod.log.

**Comment by Unrulymaster** [comment]
okay here is the new log: The script wemod-laucher is running on version 1.498
Self update skipped
The normal args list is 12 long and the full contents are:
	['/home/liam/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=275850', '--', '/home/liam/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/mnt/Linux games/steam library/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/liam/.local/share/Steam/compatibilitytools.d/GE-Proton9-1/proton', 'waitforexitandrun', "/mnt/More linux games/SteamLibrary/steamapps/common/No Man's Sky/Binaries/NMS.exe"]
GetGame
Options
Init
PrefixDir
IfWine
Proton
Enshure
IfPfx
Users
ERR:
[Errno 25] Inappropriate ioctl for device

**Comment by marvin1099** [comment]
i think i almost got it now run:
```
python
```
then in there run
```
import os
os.getlogin()
```
and report what happens

**Comment by marvin1099** [comment]
[Actually try this file (unzip)](https://github.com/user-attachments/files/17078078/wemod.zip) 
replace the file in the launcher folder and rerun the game.
After send over the new wemod.log.

**Comment by marvin1099** [comment]
@Unrulymaster please report back if that has worked.

**Comment by Unrulymaster** [comment]
@marvin1099 wemod now launches mods can be activated (not fully tested in games) it didn't request to build a dependency for no mans sky but still worked also a potential issue i don't mind is it requests a login every time i boot up the game for wemod i don't mind if that's the case but if i can help fix i'm more than happy also i can provide the log for the last launch where it ran with the game if you want it.

**Comment by marvin1099** [comment]
So it worked with the last file i send?

**Comment by Unrulymaster** [comment]
yes the last file seemed to fix the issue i also tested with a different game and it worked, the only potential issue is wemod requires a login everytime but i'm not concerned about this.

**Comment by marvin1099** [comment]
This is now updated, go and set: "SelfUpdate = true"
in the wemod.log so you get the new update (and future ones).
Also about the relogin  try to delete the wemod_data folder (in the wemod launcher folder) and see if after logging in it gets saved.

**Comment by Unrulymaster** [comment]
so awesome! works flawless thank you so much for your help!!

**Comment by marvin1099** [comment]
No prob, i will close this for now, say if any other issues appear

**Comment by Unrulymaster** [comment]
okay thank you so much again!!!

**Comment by marvin1099** [comment]
@Unrulymaster if you like to talk a bit more you can join my discord
https://discord.me/marvin1099
You don't have to but thought I give you the option

**Comment by Unrulymaster** [comment]
oh happily thank you

**Comment by Unrulymaster** [comment]
hey @marvin1099 the link says its invalid on discord

**Comment by marvin1099** [comment]
Something must be Brocken there I fix that soon,
use that link for now I just made that https://discord.gg/pNPm6yTyD2

**Comment by Unrulymaster** [comment]
sweet thanks
