### ISSUE TITLE
Is it normal for all mods to be Pro only?

### ISSUE THREAD

**Issue by ExtraDryMartini** [DaniAsh551/wemod-launcher#126]
### Describe the problem

Wemod launches with Nioh 2 just fine, game loads in background and Wemod works in the foreground.  But after clicking 'play' and the mod list loading all the mod options say Pro only.  I remember using Wemod on Windows in the same game a few years back and they weren't locked, so is my Wemod install wrong or has Wemod changed?

### Steps that will result in the problem

launch game in Steam.

### Expected results

Mods not locked behind paywall

### Logs

[wemod.log](https://github.com/user-attachments/files/17092576/wemod.log)

### System Information

Mint 22 Cinnamon 6.2.9  Kernel 6.8.0-45-generic GE proton 9-13

**Comment by marvin1099** [comment]
Well almost, it depends on the game i think and also the keyboard shortcut is reported to still work.
So after enabling the game mods try to press the displayed buttons next to the mod name.

**Comment by marvin1099** [comment]
Hope that answered your question, if not just add a comment to this issue, i will mark it a finished for now
