### ISSUE TITLE
[BUG]: We Mod Launcher Just freezes After Starting at the Login screen

### ISSUE THREAD

**Issue by luzciles** [DaniAsh551/wemod-launcher#129]
### Describe the problem

I was Trying to Login and it just freezes if i try to write My Account Login. I Could Login 1 Time but it just freezes after login.
I need to Start it a few times so it doesnt freeze at the "Loading" Screen

### Steps that will result in the problem

1.Start Game
2. Wait that Wemod Launches
3.  Akzept AGB
4.  Chose i have already an account and press the "Log In Now" Button
5. Try to write your Acc Login and it freezes

### Expected results

Start Game Wemod Launches i can Login und Use Wemod

### Logs

[wemod.log](https://github.com/user-attachments/files/17262680/wemod.log)

### System Information

Operating System: Garuda Linux 
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.3
Kernel Version: 6.11.1-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 7950X3D 16-Core Processor
Memory: 30.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 4070/PCIe/SSE2
Manufacturer: ASUS

GE-Proton9-1 - 9-15 (i tried every Version and Steam Proton to i Build every Version Toand Tried it with Download to.

### Additional context

GE-Proton9-1 - 9-15 (i tried every Version and Steam Proton to i Build every Version To and tried it with Download to.
Same Problem.

**Comment by luzciles** [comment]
1. With Other Games the same problem
2. i did that every time i switched the ge Version 
3. I deleted the bin Folder changed Nothing
4. i deleted the Data Folder changed nothing
5. Test exe works fine if i install a game with lutris/wine i have the Problem that wemod has a broken appearance
6. x11 doesnt make a difference

**Comment by marvin1099** [comment]
Have you tryed lutris with a other wine version, like geproton, or gewine

**Comment by marvin1099** [comment]
That's not good at all.
Try to start a virtual Maschine, and see if login works there.
You could also try using a live USB.
In the VM you can really only test the test exe.
So testing with lutris should work.
Or if you have a laptop you can try on that.
On a live USB you can even try to run a regular game with wemod.

If you can get past the login you can then copy the wemod_data folder to your real system.
The wemod_data folder stores your login.
So you should be able to transfer it.

**Comment by marvin1099** [comment]
Nice, that was a good idea, good to know that xwayland solved the issue.
If you have a other issue just ask.

**Comment by luzciles** [comment]
Thanks, But it wasnt a Windows VM but A Windows Server installed on Bare Metal not a virtuell Maschine "Hyper V" is the Windows Server Native Virtualisierungs Software i use for all my virtuell Linux Server. Thanks for Your Help and your fast Answers.

**Comment by marvin1099** [comment]
yep make sense, Hyper V is a windows thing, so you just meant a windows system. 
So you are running linux on top of windows (the windows hypervisor) then?
I wold not like that since i dont trust windows.
I use qemu for any vitual machines.

**Comment by luzciles** [comment]
1 I Have a Dedicated Server where Windows Server 2019 runs on It This Server is for the Virtualisierung of My Linux Servers : I Have a Adguard Home Server on Ubuntu LTS Server with DNS Encrypting for my Internal and External Network(Internet), 1 Ubuntu LTS Server With a Wireguard VPN Server for all my Mobile Devices, Then i Have a a Ubuntu LTS Server with Cube Coders Amp Software that is a Software for Creating und Managing Gaming Servers Like Minecraft or Ark oder Satisfactory Dedicated Server. THen i have a Normal PC with Garuda Linux Installed that is my Main PC. I Use WIndows Only for virtualiserung because it is easy to use and everyone can use it and my Backup SOftware  works best with windows Server und Hyper V

**Comment by luzciles** [comment]
Do you think it is possible to rewrite your software so that it runs Nativly with Wayland ? I Think these FreeSimpleGUI Package isnt supportet on Wayland i did a few tests I Launched the Game with ywayland and wemod waited until it finished loading chose the game hit the wemod play button after that i forced ywayland off und used native wayland and with that it frozed agaain but i could use the Cheats and i Heared the wemod aktivated cheats sound and they working ingame just the GUI was frozen ?

**Comment by marvin1099** [comment]
Interesting, lots of servers very nice and a Satisfactory player too, like it.
I do like Satisfactory to just don't really feel like playing a lot these days.
Also are you German by any chance (like me), kinda sound like it.
Funny, you remind me of myself a bit (only i have less servers and really tried to remove windows from all that i have), have fun with the setup then.

**Comment by marvin1099** [comment]
About the wayland thing, i think that runs the script fine, the issue is the combination of steam + wine + wemod.
The python file work fine as far as i can see. This is not a issue from the launcher if i see this correctly.
I have to do more testing to be sure but i think no rewrite can fix this, because the launcher is just a fancy program starter.
Realy i think for this to be fixed steam + wine will have to work better for wayland.
But jep have to do more testing to be shure.

But the wemod installation stuff did work under wayland right,
I'm refering to https://youtu.be/5UlVCZvIl1E?t=125 to 2:41.
If this has infact worked (the windows and buttons from 2:02 to 2:41),
then its very likely not a issue that the launcher can fix, because then its in the hands of wine and steam.

**Comment by luzciles** [comment]
Yeah that worked fine the wemod installation stuff and the building and download stuff to.
Okey i will wait hopefully it works in the future.

**Comment by marvin1099** [comment]
> Yeah that worked fine the wemod installation stuff and the building and download stuff to. Okey i will wait hopefully it works in the future.

Yea the install uses FreeSimpleGUI, it works on wayland.
Probably a wine and steam wayland issue.

**Comment by luzciles** [comment]
Yeah iam German yeah my englisch is really german like , feel the same about Satisfactory too but the 1.0 Launch is really fascinating but iam waiting for mod support until iam playing it again. I Removed Windays a feq years ago from all my Devices but for my Hyper v Host  i Tried Virtual Box ,ESXI and qemu but Hyper V from Windows has the best performance and is really eady to use and the Server variant of Windows ist after a few tweaks really good in the contex of it is windows anhd with my DNS Sevrer iam blocking all communikation i dont like inclusive Android Windows and Apple.

**Comment by luzciles** [comment]
> > Yeah that worked fine the wemod installation stuff and the building and download stuff to. Okey i will wait hopefully it works in the future.
> 
> Yea the install uses FreeSimpleGUI, it works on wayland. Probably a wine and steam wayland issue.

do you think it is possible to integrate a x11/wayland Server/Compositor into your launcher and force that for wemod too maybe in the virtuel python enviroment your are creating with your launcher ? Like a PDF File so it has it own Gui and so on and it is wayne which compositor the Client uses ? it is like what iam doing now but without the need that the PC needs to do it ? Iam no Software programmer it is a stupid idea iam sorry for that.

**Comment by marvin1099** [comment]
blocking all communication for Android, Windows and Apple, that probably works for privacy, although your still using windows, i just also don't like that i was supporting them by using their software.
But you probably have better opsec then me. I don't really block anything except adds.
Nice talking to you, i hope this gets fixed 2 a some point, but it will probably take a bit.

**Comment by luzciles** [comment]
> blocking all communication for Android, Windows and Apple, that probably works for privacy, although your still using windows, i just also don't like that i was supporting them by using their software. But you probably have better opsec then me. I don't really block anything except adds. Nice talking to you, i hope this gets fixed too a some point, but it will probably take a bit.

yeah i hope so too i dont use windows because Linux is just plain better than windows and windows really frustrated me a lot, but i windows sevrer that does nothing then hosting virtuell maschines is ok for me :D
