### ISSUE TITLE
typo in import

### ISSUE THREAD

**Issue by steadfasterX** [DaniAsh551/wemod-launcher#14]
seems this is missing a `n` in `popup_dowload` (should be "popup_dow**n**load" instead)

https://github.com/DaniAsh551/wemod-launcher/blob/main/wemod#L7

~~~
Traceback (most recent call last):
  File "/home/abc/programs/wemod-launcher/wemod", line 7, in <module>
    from util import cache, exit_with_message, get_dotnet48, popup_dowload, wine, winetricks, log, popup_execute, pip, popup_options
ImportError: cannot import name 'popup_dowload' from 'util' (/home/abc/programs/wemod-launcher/util.py)
~~~

error gone after setting it to:

`from util import cache, exit_with_message, get_dotnet48, popup_download, wine, winetricks, log, popup_execute, pip, popup_options`

**Comment by DaniAsh551** [comment]
Thank you for the headsup.

Fixed in 0c91e17
