### ISSUE TITLE
Mass Effect Legendary Edition "launch loop"

### ISSUE THREAD

**Issue by emersonrp** [DaniAsh551/wemod-launcher#15]
Because of the way Mass Effect Legendary Edition launches, in combination with WeMod's requirements for it, it can't be made to work currently.

MELE utilizes its own launcher from which you can select from ME1, ME2, or ME3.  If you try to launch one of the three games directly without using this "1/2/3" launcher, it just falls back to opening the generic EA launcher, from which you can launch the 1/2/3 launcher.  There's no way that I have found to start one of the three games without the 1/2/3 launcher.

In WeMod, the instructions for MELE require that you launch one of the three games from the 1/2/3 launcher -before- pressing "Play."  If WeMod's custom location for the .exe is set to the launcher, WeMod will start the launcher while attempting to inject the mods into the actual (as-yet unlaunched) game, and time out.  If the custom location is set to one of the games directly, as mentioned above, you get the top-level EA launcher, which will attempt to launch the game from Steam, which will switch to the running WeMod since Steam's custom launch options for MELE point there.

I'm not sure this is fixable -- what is needed is a way to launch the 1/2/3 launcher that's -not- from the WeMod "Play" button's custom location, so probably some sort of complicated Steam launch options incantation to launch WeMod and the launcher in parallel.

Is this something that's possible?

(Edit to add:  desktop Manjaro Linux)

**Comment by DaniAsh551** [comment]
What happens when you press play in WeMod after launching your desired game? (Assuming you set the exe to the game executable.)

**Comment by emersonrp** [comment]
Sorry yeah I wasn't completely clear on that -- if you set the WeMod exe location directly to the game exe, that's when it'll instead launch the generic top-level EA launcher when pressing play in WeMod.  Apparently EA doesn't want you doing that.

If you set the exe location to the 1/2/3 launcher, pressing play in WeMod starts that launcher, but the actual game can't be started fast enough to avoid WeMod timing out and failing its injection.

The trainer has a note at the top, warning that you need to launch the game from the launcher -before- pressing play, which is apparently not a lie.  To make this work, there needs to be some way to launch the game from the 1/2/3 launcher at the same time as WeMod (or before?) so that the game can be running already when you press play.

I understand this is a weird corner case, so I'm just seeing if there's any way around this that I'm not seeing.  Thanks!
