### ISSUE TITLE
PySimpleGUI

### ISSUE THREAD

**Issue by Kithkani** [DaniAsh551/wemod-launcher#17]
After step 2 may want to suggest if nothing happens to install PySimpleGUI.

Manjaro didn't have it and I seen in the log why it was failing, easy fix either way.

Thanks for the awesome tool!

**Comment by DaniAsh551** [comment]
Installations from pip shouldnt be distro-specific as far as I know. This is weird.

**Comment by DaniAsh551** [comment]
I am unable to reproduce this issue. Feel free to re-open if you can add more details and steps to reproduce.
