### ISSUE TITLE
Can’t install game

### ISSUE THREAD

**Issue by BookieC** [DaniAsh551/wemod-launcher#19]
I’m on the step where you install the .exe on WeMod, and the file directory isn’t showing the location. It doesn’t look like it’s going through Dolphin. Am I missing something?

**Comment by DaniAsh551** [comment]
When you are selecting the Game .exe on WeMod, you would be going through the Wine/Proton's file picker dialog.
This should be somewhat similar to the file picker dialog you get on Windows.
