### ISSUE TITLE
Failed to Install For Second Time

### ISSUE THREAD

**Issue by endrureza** [DaniAsh551/wemod-launcher#21]
I don't understand, i've installed wemod successfully on the first game. But when i decided to install on another game on 2 cases:

1. I chose build and wemod-launcher.

Instead of installing dot48 it's said repair or remove. i chose repair, but i ended up with failed installation at the end.

2. I chose download

I got error saying dvx or dv something installation failed.

**Comment by endrureza** [comment]
I'm trying to modify this line 

```
  # Finalize setup
  if resp == 0:
    log("Finished dependencies installation. Writing init file...")
    open(INIT_FILE, "a").close()
  else:
    exit_with_message("ERROR", "Failed dependencies installation with code '{}'. Aborting...".format(resp), resp)
```

to

```
if resp == 0 or resp == 1:
```

it works. i had no idea what is code 1. this should make sense when the dotnet is repairing. Somehow repairing and removing gives the same code. You might want to investigate this further 

Oh, and another thing, Proton 8.25 is working too. @DaniAsh551

**Comment by endrureza** [comment]
Oh another addition thing, 

```
  # Finalize the setup
  if exit_code == 0:
    log("Finished dependencies installation. Writing init file...")
    open(INIT_FILE, "a").close()
  else:
    exit_message = "dxvk and vkd3d installation failed with code '{}'".format(exit_code)
    exit_with_message("ERROR", exit_message, exit_code)
```

i think these lines require attention. Because when popun appear on the first time, you have choice either to build or download right ? i assume, download is when there is already wemod installed. but it always ended up with error `dxvk and vkd3d installation failed with code`

**Comment by TylerCode** [comment]
I can confirm all of these posts, had the same issues, bypassing the check worked.

**Comment by endrureza** [comment]
For now, i'm just building once. and for the next game to use wemod, i just choose download but you need to modify the conditional line 85 of wemod file. that condition is causing fail when choose download. I wish someone knows what's going on.

```
  # Finalize the setup
  if exit_code == 0 or exit_code == 1:
    log("Finished dependencies installation. Writing init file...")
    open(INIT_FILE, "a").close()
  else:
    exit_message = "dxvk and vkd3d installation failed with code '{}'".format(exit_code)
    exit_with_message("ERROR", exit_message, exit_code)
```

**Comment by TylerCode** [comment]
I may put some work into figuring it out on the next game I try. I initially thought the problem lied in the .NET installation but it was actually the step prior.

**Comment by DaniAsh551** [comment]
I noticed this a few times aswell, but I couldnt figure out the root cause at the time, so this has just gone unaddressed unfortunately.

Its weird, the .Net setup returns non-standard exit codes (as far as I can tell, unless I am missing something), and I couldnt find any documentation for this.

Like, in one instance, I had the setup return 147 and 13 in another case - I just could not make the heads or tails outta the situation at the time - havent taken another look at it though.

**Comment by DaniAsh551** [comment]
Closing because its been a while with no response. Please feel free to reopen if any additional information can be presented.
