### ISSUE TITLE
Not sure why

### ISSUE THREAD

**Issue by SamadKassim** [DaniAsh551/wemod-launcher#24]
hello guy, i'm new here with garuda. i follow the install tuto but when i try to launch the game, i didnt get any prompt to build or anything. the game just closed. in terminal i get this error "ERROR: ld.so: object '/home/esuke/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored." 
![Screenshot_20240223_091800](https://github.com/DaniAsh551/wemod-launcher/assets/138803851/1bff0fc6-9288-48ac-a99b-6c7a177712f1)

**Comment by DaniAsh551** [comment]
Did you wipe the prefix, then run the game once without wemod and then do the setup?
