### ISSUE TITLE
Stuck while installing WeMod on Steam Deck

### ISSUE THREAD

**Issue by dvjsol** [DaniAsh551/wemod-launcher#27]
Hi, the installer is getting stucked while I'm trying to install the application.

I'm using proton 9-1 and following the guide Build>winetricks, but the installer got stuck at "Executing load_remove_mono internal". I've waited more than 1 hour and the stuck persiste.

Any tips here? Tks.

**Comment by JohnHamwi** [comment]
Have you tried a different game?

**Comment by dvjsol** [comment]
> Have you tried a different game?

Yes, same thing with other title.

**Comment by DaniAsh551** [comment]
@dvjsol maybe your winetricks version is outdated. Try re-cloning the tool, this should download all the needed files again.

Let me know if that works or not.

**Comment by dvjsol** [comment]
> @dvjsol maybe your winetricks version is outdated. Try re-cloning the tool, this should download all the needed files again.
> 
> Let me know if that works or not.

Did that and same thing happened, stuck at step "Executing load_remove_mono internal".

**Comment by DaniAsh551** [comment]
You could add something like `WEMOD_LOG=/home/deck/wemod-launcher/wemod.log` to your game Launch Options.
This would create a log file which you could share with me. And you could also include `PROTON_LOG=1 ` and provide both the files.

**Comment by dvjsol** [comment]
@DaniAsh551 sry but I couldn´t find the proton log. The launch options has to look like this `WEMOD_LOG=/home/deck/wemod-launcher/wemod.log PROTON_LOG=1 /home/deck/wemod-launcher/wemod %command%` right?

Regarding the wemod log, follow attached.

**Comment by marvin1099** [comment]
Since there seems to be no active work right now, I will suggest the following:
1. Download the newest Proton  
    For me GE-Proton9-4 worked in the past you may want to try that one
2. delete the game prefix
3. Delete the launcher folder
4. Re-clone the launcher
5. Start the game **WITHOUT** WeMod on the new proton version
6. Close the game
7. Add back the wemod-launcher start options
8. Start the game
9. Click build
10. Then on winetricks

I know you have tried some of this but see if it works anyway and report back.

**Comment by dvjsol** [comment]
> Since there seems to be no active work right now, I will suggest the following:
> 
> 1. Download the newest Proton
>    For me GE-Proton9-4 worked in the past you may want to try that one
> 2. delete the game prefix
> 3. Delete the launcher folder
> 4. Re-clone the launcher
> 5. Start the game **WITHOUT** WeMod on the new proton version
> 6. Close the game
> 7. Add back the wemod-launcher start options
> 8. Start the game
> 9. Click build
> 10. Then on winetricks
> 
> I know you have tried some of this but see if it works anyway and report back.

@marvin1099 I tried those steps but at step 8 I'm getting this message (it's new for me and the proton is already installed in ProtonUp-Qt - Wine/Proton Installer):

"The proton 9.4 is not installed... Wanna proceed? Yes/No"

If I check "No", the installer proceed as usual and got strucked at:

"Using winetricks 20240105-next - sha256sum: 80f12d3f5f39110fa7ba083f5c08196041e5936df495fd46b18a50cb54a43648 with wine-9.0 (Staging) and WINEARCH=win64"

Any tips here? Am I doing something wrong?

**Comment by marvin1099** [comment]
Hm ... are you using protonup-qt to download the GE-Proton9.4?
If not try that (i have tested the newest version as well now so could try GE-Proton9.5 if you want).
It should look like this (but with your steam path):
![Screenshot_20240512_153918](https://github.com/DaniAsh551/wemod-launcher/assets/40715852/19de9f0c-1920-431d-b7ce-2ec7065dce5a)

**Comment by marvin1099** [comment]
If you have tried that, mabye also remove the old proton versions (or if you like to keep them put them in a other folder).
So remove all versions in you compatibility tools folder except the version you like to use (don't forget to restart steam, so you can select the proton version in the compatibility tab).
Hope this gets you somewhere, report back after that.

**Comment by dvjsol** [comment]
This is strange right?

![error](https://github.com/DaniAsh551/wemod-launcher/assets/146761958/2c2653a9-0e73-48b6-b758-2bd073add77d)

**Comment by marvin1099** [comment]
Oh got it that, just means that you have a prefix that is using version 7.35 that has wemod installed, 
clicking "No" on this is CORRECT, 
using this old version is not going to work. 
Ok so you click on "No" then "build" then "winetricks" right?
and than is it just stuck right?
Try waiting for 60 mins, seems long but it takes 25 mins on my PC and i have very decent hardver, the 20 mins are a bit short (mabye it was like that in the past).

**Comment by marvin1099** [comment]
also, will this always say "* (global)" on your device, interesting on mine it never says something about "* (global)".
The * refers to the proton versions of course.

**Comment by dvjsol** [comment]
> Also, will this always say "* (global)" on your device? If so that is interesting on mine it never says something about "* (global)". The * refers to the proton versions of course.

It says "global" when I point that proton as default on steam settings.
Just a remember that I'm using Steam Deck, ok? I'm not sure, but maybe this works differently on others Linux dist...

**Comment by marvin1099** [comment]
> > Also, will this always say "* (global)" on your device? If so that is interesting on mine it never says something about "* (global)". The * refers to the proton versions of course.
> 
> It says "global" when I point that proton as default on steam settings. Just a remember that I'm using Steam Deck, ok? I'm not sure, but maybe this works differently on others Linux dist...

On my friends steam deck it shows without global too, so a bit stange:
![IMG_20240512_180748](https://github.com/DaniAsh551/wemod-launcher/assets/40715852/3a2242b0-6b02-4d85-a5c5-e8a934061869)

**Comment by marvin1099** [comment]
> > > Also, will this always say "* (global)" on your device? If so that is interesting on mine it never says something about "* (global)". The * refers to the proton versions of course.
> > 
> > 
> > It says "global" when I point that proton as default on steam settings. Just a remember that I'm using Steam Deck, ok? I'm not sure, but maybe this works differently on others Linux dist...
> 
> On my friends steam deck it shows without global too

I found the reason, proton ge gets marked with (global) if steam is set up to use it for all windows titles by default.
So that is what you have done right? 
I was worried there is a other version.
That's fine then.
Keep me posted on your success.

**Comment by dvjsol** [comment]
Ow great to know! Tks!

I'm trying again as you said but, after ~30min, the process is still "freezed" at the same point:

"Using winetricks 20240105-next - sha256sum: 80f12d3f5f39110fa7ba083f5c08196041e5936df495fd46b18a50cb54a43648 with wine-9.0 (Staging) and WINEARCH=win64"

I'll wait till 60min so I'll report again...

**Comment by marvin1099** [comment]
Here is the deal, I'm not super familiar with wine and winetricks so if this is never getting past that message (like you say), then the only option I can give you is to send you a working WeMod prefix.
There are 2 other developers, 
but they have answered you already and they also seem to be doing lots of stuff in real live, 
so this project could some interested people
and it would help if they know their way around wine.
So this is all I could offer you.

This prefix will probably work for the entire GE-Proton9-x saga.
So you can update by simply changing the active GE-Proton version of the wine game to the newest one.

**Comment by marvin1099** [comment]
Do you need/want a copy of a working prefix?
To clarify if i give you this prefix you wont have to build since I have done so already,
you will just have to replace your current compatdata prefix folder with the one I will send you.
Just say if you want this, otherwise say how you want to continue.
If you don't say anything i will close the issue at some point.

**Comment by dvjsol** [comment]
> Do you need/want a copy of a working prefix? To clarify if i give you this prefix you wont have to build since I have done so already, you will just have to replace your current compatdata prefix folder with the one I will send you. Just say if you want this, otherwise say how you want to continue. If you don't say anything i will close the issue at some point.

I’m okay with that, can you send to me a link to download pls? And this build will work with any game? I just have to merge your folder with the one with the game right?
Tks in advance for your support!

**Comment by marvin1099** [comment]
There you go a working wemod prefix of GE-Proton9.5: [https://we.tl/t-2YzJEYEIuH](https://we.tl/t-2YzJEYEIuH)

**Comment by marvin1099** [comment]
I'm going to add back prefix downloads this will make this issue somewhat solved, if someone is interested here my are plans [Milestone 1](https://github.com/DaniAsh551/wemod-launcher/milestone/1)

**Comment by dvjsol** [comment]
@marvin1099 it worked! I just merged your folder with the one with the game at compatdata folder and worked smooth!
Tks again for your support!

**Comment by marvin1099** [comment]
Prefix downloads are now implemented,  
so now instead of building you can use the download option,  
check [pull 43](https://github.com/DaniAsh551/wemod-launcher/pull/43) for implementation and changes.
I will close this issue now.

**Comment by marvin1099** [comment]
@dvjsol If you still got the old prefix, this one (It says you have a wemod prefix on version 7.35 that is the one I'm referring to):
> ![error](https://github.com/DaniAsh551/wemod-launcher/assets/146761958/2c2653a9-0e73-48b6-b758-2bd073add77d)

Could you send it to me, I'm not able to make one that works anymore so i like to se if someone else has a old working one.

**Comment by dvjsol** [comment]
@marvin1099 sorry for the late reply, but I don´t have it anymore...

**Comment by marvin1099** [comment]
Ok then.
Not great but, also not that bad.
