### ISSUE TITLE
Issues with Steam Deck Setup

### ISSUE THREAD

**Issue by Vinny1324** [DaniAsh551/wemod-launcher#28]
Hello there, I've been trying to follow various guides to get the launcher set up but keep running into issues. For example, I couldn't get .net 4.8 to install via the winetricks > uninstall method. When I selected the exe, nothing opened. I tried multiple times.

I also tried to use other methods from other guides and it would give me errors with games like must play in Admin mode or windows 7 not supported. Any help please? I could use a real time walkthrough if possible as I'm eager to get it working and likely sub to Pro.

**Comment by Vinny1324** [comment]
If you have Discord, I would love to speak with you to go over why I'm getting all these issues. Nothing I'm doing is working despite following all the guides, sadly..

**Comment by DaniAsh551** [comment]
@Vinny1324 I think I have an idea on what might be wrong, I'll see if I can push a fix for this. Also since you mentioned pro, it's not required, but you'll definitely have an easier time if using on a Deck. Also, I am in no way affiliated with WeMod.

**Comment by Vinny1324** [comment]
I understand. If you had a Discord or something, it may make it easier to explain/show my exact issues. The staff at WeMod have been basically silent and unhelpful. My main goal is to find someone that got it working that can help me figure out what I'm doing wrong. My discord is vinny.

**Comment by DaniAsh551** [comment]
Hopefully solved by commit 0fe8667a1e8114570f21cbaddc2cbe503b2595f7

If not, please re-open
