### ISSUE TITLE
Keep installing net 4.8 

### ISSUE THREAD

**Issue by dickyocean** [DaniAsh551/wemod-launcher#3]
Hi, I followed the installation guideline and tried protontrick method to add the blank txt file called .wemod_installer. However, after I have done everything, it redirects me to install the Framework Net 4.8 again and again. I tried to use protontrick to execute the wemod.exe but no games can be found even if I logged in with my account. Please help. Thanks.

**Comment by DaniAsh551** [comment]
Assuming that you are on the "automated" branch, you could follow the following steps:
1. delete your prefix
2. make sure you use Proton-GE 7.35 during the initial launch
3. follow the instructions

I will close this issue for now - feel free to reopen if the issue persists.
