### ISSUE TITLE
[Feature] Transfer wemod to other games

### ISSUE THREAD

**Issue by marvin1099** [DaniAsh551/wemod-launcher#31]
It would be nice if it was only needed to build the wemod launcher once
and than be able to use that version on a other steam game so you dont have to recompile.
Right now it seems when i add the wemod command to new games it wants to build 
(or download but that is not going to work, obviously).
If there is a good way to tansfer wemod, than say so it just takes a while if done on all games individually. 

Maby add a section on how to transfer wemod to other games in the readme.

Thanks a bunch.

Edit: I haven't quite figured out how the script works,
but it seems you are just installing some progamms with winetrix and than running WeMod.
Something like that, so to make the transfer possible,
it may be possible to install these dependencs to the main wine instance in `/home/$USER/.wine`,
I'm not shure about that, but maby.
Just spitballing some ideas, of course copying the full wine prefix of a working WeMod game might work, 
but maby there is a better way?

Thanks in advance.

**Comment by DaniAsh551** [comment]
The standard procedure for transferring one game's proton prefix to another game still applies here.
If you simply cloned a wemod enabled prefix to another game, then it should just work.

Hope that answers your question.

**Comment by marvin1099** [comment]
I was just wondering if there is a other way to transfer wemod, than copying the prefix.

Like copying just copying a few files, if we need some depencys, that installing these to the main wine prefix and copying a few files might also work. Realy i want to know how this stuff works so then a game transfer feature could be added to the laucher.

I have some idea on how to do it actually, what we do is we add a function that copys a successfull builds wine prefix, so when the laucher starts it can check if a prefix is ready for game x that is not ready, so than we copy the working prefix to game x compat data.

Do you have a idea of what i have in mind?

Here a other way to talk about it

If gameprefix_ready and not ready_prefix_in_wemod_folder
Then copy gameprefix to wemod_folder
Elif not gameprefix_ready and ready_prefix_in_wemod_folder
Then copy ready_prefix_in_wemod_folder to gameprefix

**Comment by marvin1099** [comment]
Please reopen, this feature would be super convinient.
