### ISSUE TITLE
Unable to download mod

### ISSUE THREAD

**Issue by GrzzlyAlex** [DaniAsh551/wemod-launcher#35]
Hello, I have tried the install process a few times outlined both here and on the wemod discord but fall short regardless of the game. One the “build” is complete, I get a terminal or cmd promo box saying “hi from we mod…” and to “press any key to continue…” once I press a key and log in, there is no option to download a game mod. The game launches in the background, but wemod requires me to click “play” after searching for the game. In the guide below, I fall short on number 4 as I cannot locate any install. I imagine the installer is failing and missing some prompt box? I would appreciate any and all help!

“Step 4: Configuring WeMod Account and Installing Game Mods

1. When you launch the game now WeMod should Launch with it
2. If not logged in, log in or create an account in WeMod (One time only).
3. Search for the game you launched in WeMod.
4. Click the arrow next to install.
5.Locate the game's executable file: Navigate to /home/deck/.
6.Type in the file name ".local" and pick an exe file.
7. It should take you to the ".local" folder and then go to share/steam/steamapps/common/Game/Game.exe.“

**Comment by DaniAsh551** [comment]
The path to the correct `exe` you would need to pick should be displayed in the cmd window iirc.
