### ISSUE TITLE
Error with 'download' prefix options

### ISSUE THREAD

**Issue by markspo** [DaniAsh551/wemod-launcher#4]
Trying it with something simple, Fallout Shelter on the Steam Deck.

SSHd in on Desktop Mode, and ran:

git clone https://github.com/DaniAsh551/wemod-launcher.git -b feat/automated

which created /home/deck/wemod-launcher

Added WEMOD_LOG=/home/deck/wemod-launcher/wemod.log /home/deck/wemod-launcher/wemod %command% to the Launch Options

When I hit Play, I get the option to build or download

I select download, and it downloads the prefix, and the errors out

"Prefix unpacking failed with code '2'"

The log contains:

Unpacking prefix...
Using command 'sh -c "cat '/home/deck/wemod-launcher/.cache/wemod_prefix.tar.zst' | zstd -T0 -d -c | tar -xvf - -C '/home/deck/wemod-launcher/.cache/wemod_prefix.tar.zst'"'
Prefix unpacking failed with code '2'

Running that command in the console results in:

tar: /home/deck/wemod-launcher/.cache/wemod_prefix.tar.zst: Cannot open: Not a directory
tar: Error is not recoverable: exiting now

It looks like there is a format error in the tar command, but I don't know what the actual command is trying to accomplish, because if I remove the '- -C" it extracts the contents into the .cache folder with no issues

**Comment by markspo** [comment]
So I goofed, and didn't add the .wemod_installer to the directory.  Did a mkdir pfx | touch .wemod_installer

It installed.  Prefix is set to 7.35 and when it runs a CMD prompt opens:

Hello from WeMod Launcher
WEMOD EXE: "Z:\home\deck\wemod-launcher\wemod_bin\WeMod.exe
PWD: "Z:\home\deck\.local\share\Steam\steamapps\common\Fallout Shelter"
command: "FalloutShelter.exe"
Press any key to continue...

Pop up the keyboard, hit enter, then:

Application could not be started, or no application associated with the specified file
ShellExecuteEx failed: Path not found

**Comment by markspo** [comment]
Digging more, the download prefix does not download WeMod into wemod_bin

Also, does it does not seem to have .net 4.8

Is there a way to add that?

Sorry, still learning here

**Comment by DaniAsh551** [comment]
@markspo looks like you are right with your first comment - I will look into it soon.

`sh -c "cat '/home/deck/wemod-launcher/.cache/wemod_prefix.tar.zst' | zstd -T0 -d -c | tar -xvf - -C '/home/deck/wemod-launcher/.cache/wemod_prefix.tar.zst'"` looks like an error indeed

**Comment by DaniAsh551** [comment]
In the meantime - I suggest you try the build option with GE-Proton 7.35

**Comment by markspo** [comment]
@DaniAsh551 thanks for the reply, I'm sorry it's so scattered, I'm just putting up the issues as I face them

I am currently have the compatibility set to GE-Proton7-35.  When WeMod opens, its complaining about .net 4.8

I popped back into Desktop Mode, and opened up Protontricks, and when I attempt to add 4.8 to the current prefix, it states that it is already installed.

Am I missing something?  Am I supposed to put that PATH command into the launch options?

**Comment by DaniAsh551** [comment]
Closing the issue as this is addressed in the README now
