### ISSUE TITLE
Wemod Stuck in foreground

### ISSUE THREAD

**Issue by acleiker2** [DaniAsh551/wemod-launcher#49]
When run through game mode on a Steam Deck, wemod is stuck in front of the game. When attempting to switch windows using the steam button menu, wemod still stays in the foreground. 
This issue also occurs on a gamescope session on different hardware. 
Both on stable and preview channels of SteamOS. 

Edit:
Switching developer mode on steam deck fixes this issue.

**Comment by marvin1099** [comment]
@acleiker2 I was interested to know how to switch open windows on the steam deck gaming mode, have you managed to do that?
Can you say how you have done that?

**Comment by acleiker2** [comment]
Yeah to switch between windows in gaming mode on the Steam Deck ensure that
Developer mode is toggled on in settings. Then when you're in game, hit the
steam button and it should have a list of windows opened by the
game/process. Just select the one you want. Sometimes it doesn't work on
the first try when switching.

**Comment by marvin1099** [comment]
Cool, steam support wasn't helpfull about this, i have to check that out, if it works well i add it to the guide

> Yeah to switch between windows in gaming mode on the Steam Deck ensure that Developer mode is toggled on in settings. Then when you're in game, hit the steam button and it should have a list of windows opened by the game/process. Just select the one you want. Sometimes it doesn't work on
the first try when switching.
