### ISSUE TITLE
stuck on step 5.2

### ISSUE THREAD

**Issue by ntmontijo** [DaniAsh551/wemod-launcher#58]
Been following the guide to the letter, but when I get to the "build" or "download" buttons I click download, and nothing happens. I've attached the wemod.log output. Am I just missing something obvious?
![20240527_083229](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/96a53814-196d-41a5-8eca-d1096ff1f3aa)

**Comment by marvin1099** [comment]
It's fixed now, re-download the wemod-laucher and try once more

**Comment by ntmontijo** [comment]
Got past that step. Much appreciated!

Now wemod opens, but it doesn't load the game as well. Here is the wemod launcher output.![20240527_170139.jpg](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/d6177831-3ed4-4f1b-b5ea-6cf4d8371528)

The path to the game is correct, but the game isn't launched at the same time wemod is.

**Comment by ntmontijo** [comment]
> It's fixed now, re-download the wemod-laucher and try once more

Got past that step. Much appreciated!

Now wemod opens, but it doesn't load the game as well. Here is the wemod launcher output.![20240527_170139.jpg](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/d6177831-3ed4-4f1b-b5ea-6cf4d8371528)

The path to the game is correct, but the game isn't launched at the same time wemod is.

Here is the log output:
![20240527_171157.jpg](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/2fbbd098-10f6-47a9-8283-be34f2631a94)
