### ISSUE TITLE
Stuck on step 6.1

### ISSUE THREAD

**Issue by ntmontijo** [DaniAsh551/wemod-launcher#61]
I got past the download button issue, but a new thing has shown up. The game (in this case, South Park - The Stick of Truth) won't load alongside wemod. I get just wemod.

Here is the wemod-launcher output:
![20240527_170139.jpg](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/d3d2a5a0-c2ae-4012-b5a2-1a6b35a53638)

And here is the wemod log output:
![20240527_171157.jpg](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/8e2c2b71-c06c-4339-9af9-a723f2dd251c)

Sorry to be a bother!

**Comment by marvin1099** [comment]
Done re-download the tool then it should work.

**Comment by ntmontijo** [comment]
> Done re-download the tool then it should work.

It's still giving me the same output in the wemod launcher

**Comment by ntmontijo** [comment]
@marvin1099 I re-cloned the repo, same result

**Comment by marvin1099** [comment]
Be so kind and send the directry tree of the game, i need to check ßy suspision.
To print the tree run "cd %steamallgamesdir%" and then "find ./%gamedirname%/"

**Comment by ntmontijo** [comment]
Here is the output:
![steamallgamesdir output](https://github.com/DaniAsh551/wemod-launcher/assets/33525524/966b2ff4-db6c-4452-9701-41f7241eb36f)

**Comment by marvin1099** [comment]
almost
![here is an example for portal 2](https://github.com/DaniAsh551/wemod-launcher/assets/40715852/da5d7e9d-9d7f-4559-ab4b-c18ede61e4fe)
you will have to put in the full name in you case that looks like this: 
"South\ .......\ Whole/"
The .... will have to be filled in, out can use the tab key to make your system fill that in, 
but this only works if you have typed the beginning

**Comment by ntmontijo** [comment]
Here is the Konsole output (too big for a screenshot this time)
[find output.txt](https://github.com/DaniAsh551/wemod-launcher/files/15468861/find.output.txt)

**Comment by marvin1099** [comment]
Ok, Im going to need the steam output, to get this open a new terminal, make shure steam is not running and then type "steam" and hit enter.
After that wait for steam to load and copy the output of steam from the terminal, right after you click start on the wemod-laucher game.

**Comment by ntmontijo** [comment]
As requested:
[Steam output.txt](https://github.com/DaniAsh551/wemod-launcher/files/15469182/Steam.output.txt)

**Comment by marvin1099** [comment]
The mistake is pressent in old code from a older developer, so if things go well i have it fixed today, otherwise it might take two days.

**Comment by ntmontijo** [comment]
> The mistake is present in old code from a older developer, so if things go well i have it fixed today, otherwise it might take two days.

No worries. Let me know if i need to test anything or if you need other output from me.

**Comment by marvin1099** [comment]
Ok so i think it works now.
Re-download the toll and try it.

**Comment by marvin1099** [comment]
> Ok so i think it works now. Re-download the tool and try it.

report back if it works.

**Comment by ntmontijo** [comment]
@marvin1099 Sadly no dice. Now wemod doesnt event load, just acts like i opened and immediately cancelled load of the game

**Comment by marvin1099** [comment]
Man, ok then, make shure you are on version 1.003, and send all the logs once more (wemod.log and steam log)

**Comment by ntmontijo** [comment]
Roger, grabbing logs now

**Comment by ntmontijo** [comment]
Here is the steam output, but it didnt generate a wemod.log this time
[steamoutput.txt](https://github.com/DaniAsh551/wemod-launcher/files/15475985/steamoutput.txt)

**Comment by marvin1099** [comment]
Ok, i think i fixed it, but this time the problem might only be on some systems.
O well, as usual re-download and try once more

**Comment by ntmontijo** [comment]
trying now

**Comment by ntmontijo** [comment]
here is the output
[steam output.txt](https://github.com/DaniAsh551/wemod-launcher/files/15476244/steam.output.txt)

**Comment by marvin1099** [comment]
I still cant get the error on my system but i think now it will work on you're system for real, re-download.

**Comment by ntmontijo** [comment]
And the output:
[steamoutput.txt](https://github.com/DaniAsh551/wemod-launcher/files/15476318/steamoutput.txt)

**Comment by marvin1099** [comment]
i think this time the error is in the wemod.log

**Comment by ntmontijo** [comment]
i dont see the wemod.log file in the wemod-launcher folder

**Comment by marvin1099** [comment]
you know the drill re-download

**Comment by marvin1099** [comment]
hopefully it's good now

**Comment by ntmontijo** [comment]
checking. I redownloaded the prefix just as an added measure.

**Comment by ntmontijo** [comment]
It works in Desktop mode! Lemme check desktop mode just to be extra sure, standby

**Comment by ntmontijo** [comment]
And PAYDIRT!! You are amazing!
