### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by Syoarn** [DaniAsh551/wemod-launcher#74]
Hello,

I've been trying to get this set up for the last couple of days now and I haven't been able to get past step 4 of the full guide. Everything works fine up until this point, but as soon as I put the launcher options in the game refuses to launch at all. I've tried restarting multiple times to see if that would help, but I can never get the game started with those launcher options in either game or desktop mode.

**Comment by marvin1099** [comment]
Open a terminal, make shure steam is closed, type steam and hit enter,
after that you can send over the steam output.
Also send over the wemod.log file.

**Comment by marvin1099** [comment]
@Syoarn Do still have these problems, if so please provide the steam output and the wemod.log file

**Comment by Syoarn** [comment]
Sorry, yes I'm still having this issue. I'm in the US so it was the middle of the night then.

I wasn't sure which Steam log you wanted so this is all of the logs generated by Steam after inputting in the console. I don't see any log file though from the wemod-launcher folder? I only see what was downloaded originally.

[New Folder.zip](https://github.com/user-attachments/files/15535017/New.Folder.zip)

**Comment by marvin1099** [comment]
> Sorry, yes I'm still having this issue. I'm in the US so it was the middle of the night then.
> 
> I wasn't sure which Steam log you wanted so this is all of the logs generated by Steam after inputting in the console. I don't see any log file though from the wemod-launcher folder? I only see what was downloaded originally.
> 
> [New Folder.zip](https://github.com/user-attachments/files/15535017/New.Folder.zip)

Please Open a Terminal/Konsole, make shure steam is closed, type steam and hit enter,
after that copy the console output after starting the game.

**Comment by marvin1099** [comment]
> Sorry, yes I'm still having this issue. I'm in the US so it was the middle of the night then.
> 
> I wasn't sure which Steam log you wanted so this is all of the logs generated by Steam after inputting in the console. I don't see any log file though from the wemod-launcher folder? I only see what was downloaded originally.
> 
> [New Folder.zip](https://github.com/user-attachments/files/15535017/New.Folder.zip)

@Syoarn Please Open a Terminal/Konsole, make shure steam is closed, type steam and hit enter,
after that copy the console output after starting the game (Steam dosn't store these kinds of errors inf the log files, i need the live output)

**Comment by Syoarn** [comment]
[Steam Konsole (1).txt](https://github.com/user-attachments/files/15535662/Steam.Konsole.1.txt)

Here's that log for you with both the startup information and after the game was launched as well.

**Comment by marvin1099** [comment]
> interesting, haven't seen that problem before, its easy to solve, you probably used git with sudo when you fist downloaded the wemod laucher, so run:
> 
> ```
> chown -R deck /home/deck/wemod-launcher
> chmod -R 777 /home/deck/wemod-launcher
> ```
> 
> if any errors come up say so (you can run these with sudo, if there are problems that will probably solve it)

@Syoarn is it working?

**Comment by Syoarn** [comment]
So far it seems to be; the command you had me input let everything start up. It's building everything right now so hopefully I shouldn't run into any more issues. Thank you so much!

**Comment by marvin1099** [comment]
> So far it seems to be; the command you had me input let everything start up. It's building everything right now so hopefully I shouldn't run into any more issues. Thank you so much!

Nice, you can also download instead of using build, that is faster, that is also optional of course. One of these options will also have to be chosen of course.
