### ISSUE TITLE
Wemod fails to install or start

### ISSUE THREAD

**Issue by WolverenWerewolf** [DaniAsh551/wemod-launcher#75]
Hey there,

I recently went to update my WeMod installation with new GitHub code for re-initializing all my games that had WeMod attached to their installations.  At this point, WeMod fails to start the installation process.  I have deleted the game compatdata folders and restarted again, same issue.

The picture is the readout of the steam konsole stating that the WeMod installation has no permissions, but the cloning was done without the use of sudo.

Any help with this will be appreciated! 

![IMG_3520](https://github.com/DaniAsh551/wemod-launcher/assets/95702945/6755e164-5a76-4811-a229-2f1e12cae101)

**Comment by marvin1099** [comment]
This is the second time thos problem came up run:
```
chown -R deck /home/deck/wemod-launcher
chmod -R 777 /home/deck/wemod-launcher
```
Have you run git whit sudo, that will create this permission error you had.

**Comment by WolverenWerewolf** [comment]
Hey @marvin1099,

Yes, when I cloned (downloaded) the GitHub repo, I did not use sudo as I knew it would cause a permission issue.  I did the two commands you have listed above, unfortunely it did not resolve the issue.  I read through the prior closed tickets to see if I was missing anything before posting this issue ticket.

The last issue I saw, but I did not grab a picture of it was from the file setup.py lines 167 - 170, with it having a format syntax issue.  Just checking it now, looks like GitHub auto checked the file within the last few minutes of my writing this response (10:27 am MDT) and possibly fixed it. 

I will try redownloading the repo and checking to see if there is any issues.  I will post with my results.

**Comment by WolverenWerewolf** [comment]
I am still having permission issues, here are the logs from my deck.

Steam Konsole is the one I tried first, then ran the permission commands, and re-tried it without any luck.

Steam Konsole v2 is after I restarted the steam client and deck, still no luck with permissions.

[steam konsole.txt](https://github.com/user-attachments/files/15568482/steam.konsole.txt)
[github and permissions konsole.txt](https://github.com/user-attachments/files/15568484/github.and.permissions.konsole.txt)
[steam konsole v2.txt](https://github.com/user-attachments/files/15568481/steam.konsole.v2.txt)

**Comment by marvin1099** [comment]
You used chown twice but once it has to be chmod, just run:
```
chown -R deck /home/deck/wemod-launcher
chmod -R 777 /home/deck/wemod-launcher
```

**Comment by WolverenWerewolf** [comment]
Ah! My mistake then, I will redo the commands, thank you @marvin1099 for pointing this out!! I would have kept repeating the mistake.

**Comment by WolverenWerewolf** [comment]
Ok, we are good to go!!!  Thanks again @marvin1099 for pointing my error, everything is working as intended now!
