### ISSUE TITLE
Just Loads and Crashes After

### ISSUE THREAD

**Issue by Timmy2Toes3886** [DaniAsh551/wemod-launcher#77]
I'm trying to put WeMod on my Steam Deck. I'm using Stardew Valley to get it right now. I put in the launch options (WEMOD_LOG=/home/deck/wemod-launcher/wemod.log /home/deck/wemod-launcher/wemod %command%) and I have the force compatibility option on GE-Proton7-35, then I try to launch it but it just like crashes it doesn't open. Does anyone know how to fix this?
![ksnip_20240607-203844](https://github.com/DaniAsh551/wemod-launcher/assets/172091346/c8efb08b-0748-43c3-bd23-46f325ef0b01)
![ksnip_20240607-203930](https://github.com/DaniAsh551/wemod-launcher/assets/172091346/51af3cfc-4899-474b-be4e-f494ec30c33f)

**Comment by marvin1099** [comment]
Proton versions older then GE-Proton8 don't work anymore as far as i can see, I haven't  had any reports on this, for me versions older then GE-Proton8 don't work.

**Comment by marvin1099** [comment]
You may also want to update your wemod launcher since i see you are using the old launch options well so it stands to reason that you may be on a old version and want to update.

**Comment by Timmy2Toes3886** [comment]
What is the new launch option?

**Comment by marvin1099** [comment]
You can check the github readme and the github wiki for the newest info.
Right now the fist part of the command is not needed, but is not a problem, you can still have the first part its just not needed.
So in the newest command you can use is just `/home/$USER/wemod-launcher %command%` so the fist part (WEMODLOG=$logpath)  is no longer needed.
Also replace $USER with your username.

**Comment by Timmy2Toes3886** [comment]
Since I'm on a Steam deck would it just be /home/deck ?

**Comment by Timmy2Toes3886** [comment]
I changed the launch options and I changed the Proton version and it still does the same thing loads then crashes.

**Comment by marvin1099** [comment]
The user on a steamdeck is called `deck` yes.  
So in your case the command is just `/home/deck/wemod-launcher/wemod %command%`.  
But as i mentioned the old command still works as well,  
the reason i mentioned it is just because thought your wemod-laucher is is not on the newest version.

**Comment by Timmy2Toes3886** [comment]
How would I update the WeMod launcher?

**Comment by marvin1099** [comment]
run:
```
cd /home/deck/wemod-launcher
git pull
```
if a error comes up say so

**Comment by Timmy2Toes3886** [comment]
I ran it and it says that the launcher is up to date.

**Comment by marvin1099** [comment]
good try it now if it dosnt work im going to need the error.
to do this make sure steam is closed then run `steam`.
Then start the game and copy the teminal output of steam.
Also im going to need the `wemod.log` file if it exists.
Its at /home/deck/wemod-launcher/wemod.log

**Comment by Timmy2Toes3886** [comment]
I tried to run it and it still doesn't work. So I ran the command and opened stardew valley it didnt start. This is the output, Fossilize INFO: Setting autogroup scheduling.
/bin/sh\0-c\0/home/deck/wemod-launcher/wemod /home/deck/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=413150 -- /home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-1'/proton waitforexitandrun  '/home/deck/.local/share/Steam/steamapps/common/Stardew Valley/Stardew Valley.exe'\0
chdir "/home/deck/.local/share/Steam/steamapps/common/Stardew Valley"
ERROR: ld.so: object '/home/deck/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/bin/sh: line 1: /home/deck/wemod-launcher/wemod: Permission denied
Uploaded AppInterfaceStats to Steam
The wemod.log file does not exists.

**Comment by marvin1099** [comment]
Right so you have just missed a step in the full guide (under step 3):
[Full Guide](https://github.com/DaniAsh551/wemod-launcher/wiki/Full-guide)
you have to run:
```
sudo chown -R $USER /home/$USER/wemod-launcher
sudo chmod -R 777 /home/$USER/wemod-launcher
```
after downloading the wemod-laucher

**Comment by Timmy2Toes3886** [comment]
Oh my god it works thank you so much for the help.

**Comment by Timmy2Toes3886** [comment]
I did those 2 commands and launched the game and I got the build message.

**Comment by marvin1099** [comment]
> I did those 2 commands and launched the game and I got the build message.

Nice, when asked to download or build you can also use download, that's faster, but building works to (on most systems)

**Comment by Timmy2Toes3886** [comment]
So I got the WeMod up and running but when I go to turn on a mod it turns on but in the game it doesn't work, like for unlimited money it doesn't work.

**Comment by marvin1099** [comment]
> So I got the WeMod up and running but when I go to turn on a mod it turns on but in the game it doesn't work, like for unlimited money it doesn't work.

Sounds like a WeMod issue not a issue of the wemod-launcher, 
But i will check some stuff later after i have im done sleeping 
Try it maby on some other games abd check the full guide or the video tutorial, these are linked on the gitub readme, 
but if it wont work its possible that you found a game that dosn't work (at this point at least)

**Comment by marvin1099** [comment]
> So I got the WeMod up and running but when I go to turn on a mod it turns on but in the game it doesn't work, like for unlimited money it doesn't work.

I tested raft and it works just fine still, this means this might be a wemod issue, in that case you can check if the wemod community has a problem like that. You can find most of them on the wemod forums.
