### ISSUE TITLE
Crashing my pc/steam deck on mod launch

### ISSUE THREAD

**Issue by Masonxrr** [DaniAsh551/wemod-launcher#78]
every time i launch a game/castle crashers it freezes my pc/steam deck and i have to power it off to restart

**Comment by marvin1099** [comment]
ok that might be hard to debug, have you tryed to launch the game without wemod, and have you followed the full gude in the wiki.
If you can im going to need you to make shure steam is closed, start a console, run `steam`, then lanuch your game and copy the steam konsole output and post it here, if the wemod.log file exists then post this file in here as well.

**Comment by marvin1099** [comment]
i think your are having the same issue as [issue 79](https://github.com/DaniAsh551/wemod-launcher/issues/79) so please just be patient until i have found the problem

**Comment by marvin1099** [comment]
I think i have fixed it in [this commit](https://github.com/DaniAsh551/wemod-launcher/commit/b02a0a6fb36f437a4e2a52d9bdb36a59578c18bc), update to the newest version by running `git pull` inside the launcher folder or delete the old launcher and rerun the git command.

**Comment by Masonxrr** [comment]
fixed tysm :)
