### ISSUE TITLE
nothing happens when launching a game

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [DaniAsh551/wemod-launcher#79]
did all the previous steps, hit launch in steam and nothing happens.
steam says the game is running but no popup and no game window.

also, in system monitor every two seconds i see that it spams eight new python scripts so you end up with a hundred of them running.

[steam log](https://github.com/user-attachments/files/15812760/steam.log)
[wemod.log](https://github.com/user-attachments/files/15812761/wemod.log)

**Comment by taylor-shift** [comment]
Having same issue

**Comment by marvin1099** [comment]
I'm doing some testing right now.

**Comment by marvin1099** [comment]
I think i have fixed it in [this commit](https://github.com/DaniAsh551/wemod-launcher/commit/b02a0a6fb36f437a4e2a52d9bdb36a59578c18bc), update to the newest version by running `git pull` inside the launcher folder or delete the old launcher and rerun the git command.

**Comment by Salvodif** [comment]
same here unfortunately

**Comment by marvin1099** [comment]
> same here unfortunately

Still?
Have you updated to 1.052 ?

**Comment by Salvodif** [comment]
> > same here unfortunately
> 
> Still? Have you updated to 1.052 ?

I got latest version... so either I got some configuration wrong or it doesn't start at all

**Comment by marvin1099** [comment]
Try it now

**Comment by Salvodif** [comment]
> Try it now (of course update before you try it) Also run
> 
> ```
> sudo chown -R $USER /home/$USER/wemod-launcher
> sudo chmod -R 777 /home/$USER/wemod-launcher
> ```

I done this... let me try to make a small video and share it. Ok?

**Comment by marvin1099** [comment]
A video is not needed, its more useful if you first try to launch the game without wemod, make sure you followed the full gude in the wiki, make sure steam is closed, start a console, run `steam`, then launch your game and copy the steam console output and post it here, if the wemod.log file exists then post this file in here as well.

**Comment by Salvodif** [comment]
I thought making a video was the best option but it would actually be very long so I'll try to put all the info here
My system is:
OS -> EndeavourOS
├ -> rolling rolling
├ -> Linux 6.9.4-zen1-1-zen
├󰏖 -> 1570 (pacman)
└ -> fish 3.7.1

I followed the full guide, so:
protonup-qt v.2.9.2
GE-Proton 9-7
protontricks (1.11.1)
Zip 3.0
UnZip 6.00
tk 8.6.14-3
python 3.12.3-1
python-packaging 24.0-1
python-pip 24.0-2
python-pyqt5 5.15.10-2

3 - Installing WeMod Launcher
blackpraedicator@Glamdring ~> sudo chown -R blackpraedicator /home/blackpraedicator/wemod-launcher/
blackpraedicator@Glamdring ~> sudo chown -R 777 /home/blackpraedicator/wemod-launcher/

drwxr-xr-x 777              blackpraedicator 1.1 MB Sat Jun 15 20:32:33 2024  wemod-launcher

4 - Configure Steam
Launch Options: gamemoderun PROTON_USE_WINED3D=1 /home/blackpraedicator/wemod-launcher/wemod %command%


I wish having game loggers but cannot find it

**Comment by Salvodif** [comment]
Ok it starts
I chose 'build' with 'wintricks', it downloads what it needs to download

![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/0f612b7e-7c5f-40c8-8dfb-6c90fb9363da)

but it terminates with: Failed dependency installation with code 1

**Comment by marvin1099** [comment]
@Salvodif Use the download prefix option

**Comment by marvin1099** [comment]
@Salvodif is it working now?

**Comment by C4PTRAMPAGE** [comment]
well i got it working, once, then every time after that when i hit play in wemod the game crashes.
by the way building doesn't work it fails at dotnet48 (not in these logs)
 
[steam log](https://github.com/user-attachments/files/15855658/steam.log)
[wemod.log](https://github.com/user-attachments/files/15855659/wemod.log)

**Comment by Salvodif** [comment]
@C4PTRAMPAGE @marvin1099 

I used the download option and this is what happened.

First of wall I got this and I pressed "Yes"

![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/4be49591-ad07-49cd-8043-1792ff0d35db)

Then I got this error
![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/d9347801-302d-4f27-9200-9ee9a333ada0)


the computer started to grind, steam reported the game as running, but I could not see it and had no WeMod window.
Plus it opened an msdn url for me but I missed the link... anyway it looked to me like something about .net

Now when I relaunch the game I no longer get any options from WeMod

**Comment by marvin1099** [comment]
Ok @Salvodif from you im going to need the wemod log now.
I can see in the steam log that the wemod.log file was created (i see it because there was no error)

**Comment by marvin1099** [comment]
@C4PTRAMPAGE you should validate the steam game files and delete the /home/rampage/wemod-launcher/wemod_bin/wemod.exe then it will redownload wemmod, also try on a other game, if it works on other games then it is a wemod problem not a wemod laucher problem, in that case you want to reach out to the wemod forums to see if other people are having this problem.

**Comment by BothimTV** [comment]
I also had issues with these infinite processes, but after I updated nothing happens
It starts and instantly crashed again
https://gist.github.com/BothimTV/bde7560aa70395553eccf9e22b1753d5

**Comment by marvin1099** [comment]
I'm going to need the wemod.log file, the steam console out is only used in case of critical errors.

**Comment by BothimTV** [comment]
> I'm going to need the wemod.log file, the steam console out is only used in case of critical errors.
As I looked into the wemod log I noticed I was missing tkinter, it's working now

**Comment by marvin1099** [comment]
Closing this issue since it seems to be fixed, if there are more problems feel free to open a other issue.
