### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by dvjsol** [DaniAsh551/wemod-launcher#8]
I'm facing an issue at step 4.2 (_If not logged in, log in or create an account in WeMod (One time only)_). The keyboard doesn´t work, nor virtual or physical (USB). It does show, but I can´t type my username/password. I've tried in gaming mode and desktop mode and the issue persist. Something strange is that I have 3 others games 100% working with it, but this one particularly is having this issue. Is there anything else that I can do?

**Comment by DaniAsh551** [comment]
If you have this issue with a specific game only, then I am not sure. You could mention the problem and the name of the game in the WeMod discord channel, and see if others have the same experience as you.

You can join the discord server here: https://discord.gg/pM4Zfyn8

I personally don't own a Steam Deck - so cannot verify.
