### ISSUE TITLE
Game doesn't show

### ISSUE THREAD

**Issue by Salvodif** [DaniAsh551/wemod-launcher#80]
I thought making a video was the best option but it would actually be very long so I'll try to put all the info here
My system is:
OS -> EndeavourOS
├ -> rolling rolling
├ -> Linux 6.9.4-zen1-1-zen
├󰏖 -> 1570 (pacman)
└ -> fish 3.7.1

I followed the full guide, so:
protonup-qt v.2.9.2
GE-Proton 9-7
protontricks (1.11.1)
Zip 3.0
UnZip 6.00
tk 8.6.14-3
python 3.12.3-1
python-packaging 24.0-1
python-pip 24.0-2
python-pyqt5 5.15.10-2

3 - Installing WeMod Launcher
blackpraedicator@Glamdring ~> sudo chown -R blackpraedicator /home/blackpraedicator/wemod-launcher/
blackpraedicator@Glamdring ~> sudo chown -R 777 /home/blackpraedicator/wemod-launcher/

drwxr-xr-x 777 blackpraedicator 1.1 MB Sat Jun 15 20:32:33 2024  wemod-launcher

4 - Configure Steam
Launch Options: gamemoderun PROTON_USE_WINED3D=1 /home/blackpraedicator/wemod-launcher/wemod %command%

```
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 7402
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
BRefreshApplicationsInLibrary 1: 0ms
BuildCompleteAppOverviewChange: 153 apps
RegisterForAppOverview 1: 3ms
RegisterForAppOverview 2: 3ms
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.550.90.07 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/blackpraedicator/.local/share/Steam/ubuntu12_32:/home/blackpraedicator/.local/share/Steam/ubuntu12_32/panorama:/usr/lib32:/usr/lib/libfakeroot:/usr/lib", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
Fossilize INFO: Setting autogroup scheduling.
Fossilize INFO: Setting autogroup scheduling.
chdir "/home/blackpraedicator/.local/share/Steam/steamapps/common/Bayonetta"
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
env: '/home/blackpraedicator/wemod-launcher/wemod': Permission denied
Adding process 8859 for gameID 460790
Uploaded AppInterfaceStats to Steam
Removing process 8859 for gameID 460790
```

I saw a "permission denied" and fixed the chown and chmod error with

```
sudo chown -R $USER /home/$USER/wemod-launcher
sudo chmod -R 777 /home/$USER/wemod-launcher
```
Then WeMod started and I used the download option and this is what happened.

First of wall I got this and I pressed "Yes"
![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/d5a9ae31-a261-4d06-b9a8-5da352736794)

Then I got this error
![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/f2f9ea6a-cec5-42d9-92ab-fd1db85f5ebb)

the computer started to grind, steam reported the game as running, but I could not see it and had no WeMod window.
Plus it opened an msdn url for me but I missed the link... anyway it looked to me like something about .net

Now when I relaunch the game I no longer get any options from WeMod.

On the terminal I've this
[Terminal log](https://gist.github.com/Salvodif/6208ac505aa2056396b85b96bdda58c8)

while mine WeMod log is this: https://gist.github.com/Salvodif/66fd9056e3d6dc0b5773e37de9bb7d14

Thank you

**Comment by marvin1099** [comment]
Ok so make sure the game start without WeMod first, if the game starts without WeMod then I'm not sure about the problem yet.

**Comment by Salvodif** [comment]
yes it start with GE-Proton 9-7.

I could uninstall the game, delete its directory, reinstall it and start it with WeMod, but this time I will press download instead of build

**Comment by Salvodif** [comment]
Nope it's not fixed.
I replayed at your question: so make sure the game starts without WeMod first

**Comment by marvin1099** [comment]
Oh ok then, i going to need the new logs (from wemod.log), then.
If there is no entry for the new version then i need the steam console output.

**Comment by marvin1099** [comment]
your problem may also be related to some file problems so also run this 
```
cd /home/blackpraedicator/.local/share/Steam/steamapps/common/
find ./Bayonetta/*
```
and send the output.

**Comment by Salvodif** [comment]
I have changed a few things in my system, I need to figure out how I can recreate the WeMod logs. thanks

**Comment by marvin1099** [comment]
If the wemod.log file is missing after trying to run the game with wemod, i will need you to stop steam, run `steam` in the console and then i will need that output instead

**Comment by Salvodif** [comment]
Ok, this is my [steam log]([url](https://gist.github.com/Salvodif/f451869a676c970962c0822de9d95579))
Sadly WeMod doesn't start

**Comment by marvin1099** [comment]
> Ok, this is my [steam log](https://gist.github.com/Salvodif/f451869a676c970962c0822de9d95579) Sadly WeMod doesn't start

@Salvodif I forgot to mention you will have to try and start the game while the console is opened so the start error gets printed into the steam console, i don't think you have done that, please do that so i can tell you how to fix it

**Comment by Salvodif** [comment]
> t think you have done that, please do that so i can tel

I done it too

**Comment by marvin1099** [comment]
Oh yes i missed that sorry, but that was already fixed actually (but i fixed that today so not long ago)

**Comment by marvin1099** [comment]
and since you have mentioned it if you like to use gamemode with the wemod-laucher then do it like this:
```
gamemode /home/blackpraedicator/wemod-launcher/wemod %command%
``` 

not like this:
```
/home/blackpraedicator/wemod-launcher/wemod gamemode %command%
``` 

and yes grab the newest version

**Comment by Salvodif** [comment]
> and yes grab the newest version

```
XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xe2f64dc0
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xe2f63500
/usr/share/themes/Adwaita/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Adwaita/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant
CAppInfoCacheReadFromDiskThread took 21 milliseconds to initialize
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 30059
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
BRefreshApplicationsInLibrary 1: 0ms
BuildCompleteAppOverviewChange: 152 apps
RegisterForAppOverview 1: 3ms
RegisterForAppOverview 2: 3ms
x86_64-linux-gnu-capsule-capture-libs: warning: Dependencies of libnvidia-pkcs11.so.550.90.07 not found, ignoring: Missing dependencies: Could not find "libcrypto.so.1.1" in LD_LIBRARY_PATH "/home/blackpraedicator/.local/share/Steam/ubuntu12_32:/home/blackpraedicator/.local/share/Steam/ubuntu12_32/panorama:/usr/lib32:/usr/lib/libfakeroot:/usr/lib", ld.so.cache, DT_RUNPATH or fallback /lib:/usr/lib
fsync: up and running.
chdir "/home/blackpraedicator/.local/share/Steam/steamapps/common/Bayonetta"
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 30976 for gameID 460790
Adding process 30977 for gameID 460790
Adding process 30979 for gameID 460790
Adding process 30980 for gameID 460790
Adding process 30981 for gameID 460790
Adding process 30984 for gameID 460790
Adding process 30983 for gameID 460790
Adding process 30986 for gameID 460790
Adding process 30989 for gameID 460790
Adding process 30990 for gameID 460790
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Adding process 30991 for gameID 460790
Adding process 30992 for gameID 460790
Adding process 30993 for gameID 460790
Adding process 30995 for gameID 460790
Adding process 30996 for gameID 460790
Adding process 30997 for gameID 460790
Adding process 31000 for gameID 460790
Adding process 30999 for gameID 460790
Adding process 31002 for gameID 460790
Adding process 31005 for gameID 460790
Adding process 31006 for gameID 460790
Adding process 31008 for gameID 460790
Adding process 31009 for gameID 460790
Adding process 31010 for gameID 460790
Adding process 31011 for gameID 460790
Adding process 31014 for gameID 460790
Adding process 31013 for gameID 460790
Adding process 31016 for gameID 460790
Adding process 31019 for gameID 460790
Adding process 31020 for gameID 460790
Adding process 31027 for gameID 460790
Adding process 31033 for gameID 460790
The wemod script wemod-laucher is running on version 1.068
Failed to fetch releases.

ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/blackpraedicator/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/flatpak: /home/blackpraedicator/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/bin/flatpak)
/usr/bin/flatpak: /home/blackpraedicator/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libappstream.so.5)
/usr/bin/flatpak: /home/blackpraedicator/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/libostree-1.so.1)

Adding process 31034 for gameID 460790
Adding process 31035 for gameID 460790
Adding process 31041 for gameID 460790
Uploaded AppInterfaceStats to Steam
Removing process 31041 for gameID 460790
Removing process 31035 for gameID 460790
Removing process 31034 for gameID 460790
Removing process 31033 for gameID 460790
Removing process 31027 for gameID 460790
Removing process 31020 for gameID 460790
Removing process 31019 for gameID 460790
Removing process 31016 for gameID 460790
Removing process 31013 for gameID 460790
Removing process 31014 for gameID 460790
Removing process 31011 for gameID 460790
Removing process 31010 for gameID 460790
Removing process 31009 for gameID 460790
Removing process 31008 for gameID 460790
Removing process 31006 for gameID 460790
Removing process 31005 for gameID 460790
Removing process 31002 for gameID 460790
Removing process 30999 for gameID 460790
Removing process 31000 for gameID 460790
Removing process 30997 for gameID 460790
Removing process 30996 for gameID 460790
Removing process 30995 for gameID 460790
Removing process 30993 for gameID 460790
Removing process 30992 for gameID 460790
Removing process 30991 for gameID 460790
Removing process 30990 for gameID 460790
Removing process 30989 for gameID 460790
Removing process 30986 for gameID 460790
Removing process 30983 for gameID 460790
Removing process 30984 for gameID 460790
Removing process 30981 for gameID 460790
Removing process 30980 for gameID 460790
Removing process 30979 for gameID 460790
Removing process 30977 for gameID 460790
Removing process 30976 for gameID 460790

```

I removed "gamemode" for now

**Comment by Salvodif** [comment]
> and is it working?

no, I press download and this is the log

[wemod.log](https://github.com/user-attachments/files/15903203/wemod.log)

**Comment by marvin1099** [comment]
Ok try to delete the wemod.conf file, and download the newest version, then try once more

**Comment by Salvodif** [comment]
> Ok try to delete the wemod.conf file, download the newest version and then try once more

![Screenshot from 2024-06-19 18-08-35](https://github.com/DaniAsh551/wemod-launcher/assets/107290/8a36665a-6b17-4184-9854-3259850c0f1c)

**Comment by marvin1099** [comment]
can you try it 2 more times but don't delete the directory this time, just run 
```
cd /home/blackpraedicator/wemod-launcher/
git pull
```

this will update to the newest version.
if the error comes up twice in a row on the same version i will have to do more testing.

**Comment by marvin1099** [comment]
I have found the problem now, thans it turns out it was a long running problem now just run:
```
cd /home/blackpraedicator/wemod-launcher/
git pull
rm wemod.conf
```

**Comment by marvin1099** [comment]
@Salvodif i missed something about this problem but now it should actually work, try it, just follow the instructions above

**Comment by Salvodif** [comment]
> @Salvodif i missed something about this problem but now it should actually work, try it, just follow the instructions above

Still a error
[wemod.log](https://github.com/user-attachments/files/15904052/wemod.log)

**Comment by marvin1099** [comment]
> > @Salvodif i missed something about this problem but now it should actually work, try it, just follow the instructions above
> 
> Still a error [wemod.log](https://github.com/user-attachments/files/15904052/wemod.log)

please run this once more:
```
cd /home/blackpraedicator/wemod-launcher/
git pull
rm wemod.conf
```

now it work on my pc also, there was a unzip problem i also had to track down.

**Comment by Salvodif** [comment]
> > > @Salvodif i missed something about this problem but now it should actually work, try it, just follow the instructions above
> > 
> > 
> > Still a error [wemod.log](https://github.com/user-attachments/files/15904052/wemod.log
> 
> please run this once more:
> 
> ```
> cd /home/blackpraedicator/wemod-launcher/
> git pull
> rm wemod.conf
> ```
> 
> now it work on my pc also, there was a unzip problem i also had to track down.
> 
> if `git pull` works it will pit out sothing like: x files changed, y insertions(+), z deletions(-)
> 
> where x y and z are some numbers

```
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 7 (delta 5), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (7/7), 1.42 KiB | 1.42 MiB/s, done.
From https://github.com/DaniAsh551/wemod-launcher
   3a475b8..038ad2d  main       -> origin/main
   3a475b8..038ad2d  dev        -> origin/dev
Updating 843e10d..038ad2d
error: Your local changes to the following files would be overwritten by merge:
	coreutils.py
	mainutils.py
	readme.md
	wemod
Please commit your changes or stash them before you merge.
Aborting

```

[wemod.log](https://github.com/user-attachments/files/15904195/wemod.log)

**Comment by marvin1099** [comment]
oh yes that has failed run
```
cd /home/blackpraedicator/wemod-launcher/
rm wemod.conf
git reset --hard origin
git pull
```

**Comment by Salvodif** [comment]
[wemod.log](https://github.com/user-attachments/files/15904287/wemod.log)

New error, plus is mandatory doing
```
sudo chown -R $USER /home/$USER/wemod-launcher/
sudo chmod -R 777 /home/$USER/wemod-launcher
```

after git

**Comment by marvin1099** [comment]
rerun
```
git pull
```
and retry

**Comment by marvin1099** [comment]
@Salvodif is it working now?

**Comment by marvin1099** [comment]
I believe this has now been fixed, therefore i will close this issue if any more issue come up then just say so and i reopen this.

**Comment by Salvodif** [comment]
Still doesn't

![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/083d0ffe-5e4b-4eae-959d-e9c3a2831851)

https://learn.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=rundll32.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0

**Comment by marvin1099** [comment]
Thats a soft (so a error that can be ignored since it works anyway) error just click no on these, it should work anyway

**Comment by Salvodif** [comment]
I just relaunched the game and got a brand new error

![image](https://github.com/DaniAsh551/wemod-launcher/assets/107290/3541f5d3-1528-4edd-b266-d9edd8d3bca7)

[wemod.log](https://github.com/user-attachments/files/15909977/wemod.log)

**Comment by marvin1099** [comment]
I made shutil global, so the error should vanish after the new update

**Comment by Salvodif** [comment]
still error
[wemod.log](https://github.com/user-attachments/files/15910429/wemod.log)

**Comment by marvin1099** [comment]
realy always update with this, for some reason some of your downloaded files seem to change on disk after download, this will also reset the files, then it should work
```
cd home/$USER/wemod-launcher
git reset --hard origin
git pull
sudo chmod -R ug+x .
```

**Comment by Salvodif** [comment]
it's workinggggggggggggggggggg

**Comment by marvin1099** [comment]
Perfect
