### ISSUE TITLE
Error when starting, showing that name 'log' is not defined

### ISSUE THREAD

**Issue by cristihot** [DaniAsh551/wemod-launcher#81]
Hello,

Trying to start wemod launcher version 1.057 and after a few seconds i recieve "NameError: name 'log' is not defined"

**The wemod script wemod-laucher is running on version 1.057

Traceback (most recent call last):
  File "/home/deck/wemod-launcher/wemod", line 7, in <module>
    from setup import main
  File "/home/deck/wemod-launcher/setup.py", line 7, in <module>
    from util import download_progress, pip, log, show_message
  File "/home/deck/wemod-launcher/util.py", line 126, in <module>
    BASE_STEAM_COMPAT = get_compat()
                        ^^^^^^^^^^^^
  File "/home/deck/wemod-launcher/util.py", line 112, in get_compat
    exit_with_message(
  File "/home/deck/wemod-launcher/util.py", line 37, in exit_with_message
    show_message(exit_message, title, timeout)
  File "/home/deck/wemod-launcher/util.py", line 49, in show_message
    log(message)
    ^^^
NameError: name 'log' is not defined**

And from the wemod.log i have this text:

**WeModLog path was not given or invalid using path 'wemod.log'
If you don't want to generate a logfile use WEMOD_LOG='' or set the config to WeModLog=''
Adding script name to config
Adding script version to config
The script wemod-laucher is running on version 1.057
FreeSimpleGUI is missing
requests is missing
Dependencies missing
Trying to install Dependencies...
pip not found. Downloading...
Externally managed environment detected.
Creating virtual environment...
Virtual environment created successfully.
pip finished
Re-running script within virtual environment,
the command used is:
['/home/deck/wemod-launcher/wemod_venv/bin/python', '/home/deck/wemod-launcher/wemod']
The script wemod-laucher is running on version 1.057
FreeSimpleGUI is missing
requests is missing
Dependencies missing
Trying to install Dependencies...
Ensuring virtual environment...
Virtual environment created successfully.
pip finished
Re-running script within virtual environment,
the command used is:
['/home/deck/wemod-launcher/wemod_venv/bin/python', '/home/deck/wemod-launcher/wemod']**

Thank you!
Cheers!

**Comment by marvin1099** [comment]
Fixed

**Comment by marvin1099** [comment]
Closing this issue since it seems to be fixed, if there are more problems feel free to open a other issue.
