### ISSUE TITLE
Problems when using it on Elden Ring 

### ISSUE THREAD

**Issue by SREXz** [DaniAsh551/wemod-launcher#84]
WeMod starts but give of this error message
You need to have the correct version of the .NET framework installed

**Comment by marvin1099** [comment]
It seems you might have a old version of wemod installed on that prefix,
you will need to delete the compat folder (wine folder) of elden ring for that:

    Open Protontricks and note the "Game ID" next to the game.
    Open Dolphin file manager and enable "Show Hidden Files".
    Navigate to the .steam directory. Most of the time it's at /home/$USER. Its the drive where you installed your game.
    Then go too these sub-folders: steam/steamapps/compatdata/$GameID
    NOTE: $USER will need to be replaced with your username.
    steam/steamapps/compatdata/$GameID
    NOTE: $GameID will need to be replaced with the game id.
    Delete the folder with the corresponding Game ID.

**Comment by SREXz** [comment]
Okay wemod launches but when trying to start the mod it says: We're having trouble starting or finding your opened game.

**Comment by SREXz** [comment]
Found the problem, start_protected_game.exe was named start_protected_game2.exe.not since I wanted to launch without anti-cheat but that made it not visible for your launcher. Still, thank you very much for your fast reply and clear instructions.

**Comment by SREXz** [comment]
Found the problem, start_protected_game.exe was named start_protected_game2.exe.not since I wanted to launch without anti-cheat but that made it not visible for your launcher. Still, thank you very much for your fast reply and clear instructions.
