### ISSUE TITLE
WeMod will not load, but launches

### ISSUE THREAD

**Issue by TdotOh** [DaniAsh551/wemod-launcher#85]
"an error occured while loading WeMod You may need to reinstall the app or allow it through your anti-virus software."

this is probably my fault. but ive tried reinstalling and launching on different proton versions so im at a loss.

**Comment by marvin1099** [comment]
Try to delete the prefix of your game,
You can do this like this:

    Open Protontricks and note the "Game ID" next to the game.
    Open Dolphin file manager and enable "Show Hidden Files".
    Navigate to the .steam directory. Most of the time it's at /home/$USER. Its the drive where you installed your game.
    Then go too these sub-folders: steam/steamapps/compatdata/$GameID
    NOTE: $USER will need to be replaced with your username.
    On SteamOS, this will be:
    steam/steamapps/compatdata/$GameID
    NOTE: $GameID will also need to be replaced with the game id.
    Delete the folder with the corresponding Game ID.

Also try to delete the WeMod.exe file in /home/$USER/wemod-launcher/wemod_bin

**Comment by TdotOh** [comment]
fixed by following above then forcing ge-proton9-7. however wemod launches behind game (Crime Boss Rockay City).  marking as closed as my original issue is solved
