### ISSUE TITLE
Cannot Complete Installation on Steam Deck

### ISSUE THREAD

**Issue by KingMiyo** [DaniAsh551/wemod-launcher#86]
Uhm, first time doing this so apologies if I mess something up.

I'm trying to put WeMod on my SteamDeck for FaeFarm.
I downloaded GE Proton 9.7.
I have forced compatibility and used the correct launch options.

When the wemod installer opens and starts, it gets to like... using native overrides for the dxgi thing and then it says it cannot complete because of error 1. No idea what that means but I know the dotnet.48 follows this so i'm assuming its that.

The only weird thing is when I tried to use `sudo chmod -R ug+x /home/deck/wemod-launcher`, after putting in my password, nothing happens. Like, I don't get anything back on the log and I don't know if its supposed to work like that or not.

I don't really know where to go from here. I've deleted the prefix folder several times. I've deleted and redownloaded the wemod launcher several times. I've run the command to update it and it says I'm on the most recent version... I'm stumped at this point.

**Here is the log:**
WeModLog path was not given or invalid using path 'wemod.log'
If you don't want to generate a logfile use WEMOD_LOG='' or set the config to WeModLog=''
Adding script name to config
Adding script version to config
The script wemod-laucher is running on version 1.125
Package 'FreeSimpleGUI' is missing
Package 'requests' is missing
pip not found. Downloading...
Externally managed environment detected.
Virtual environment created successfully.
Pip finished
No updates available
Re-running script within virtual environment or to update with the command:
    ['/home/deck/wemod-launcher/wemod_venv/bin/python', '/home/deck/wemod-launcher/wemod', '/home/deck/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2230110', '--', '/home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton', 'waitforexitandrun', '/home/deck/.local/share/Steam/steamapps/common/Fae Farm/FaeFarmClient.exe']

The rerun was started
The script wemod-laucher is running on version 1.125
No updates available
The normal args list is 12 long and the full contents are:
    ['/home/deck/.local/share/Steam/ubuntu12_32/reaper', 'SteamLaunch', 'AppId=2230110', '--', '/home/deck/.local/share/Steam/ubuntu12_32/steam-launch-wrapper', '--', '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point', '--verb=waitforexitandrun', '--', '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/proton', 'waitforexitandrun', '/home/deck/.local/share/Steam/steamapps/common/Fae Farm/FaeFarmClient.exe']
Looking for init file '/home/deck/.local/share/Steam/steamapps/compatdata/2230110/pfx/.wemod_installer'
Loking for compatible wine prefixes in '/home/deck/.local/share/Steam/steamapps/compatdata' with proton version '9.7'
No compatible Proton version found in the compatibility folder.
No versions to copy available
Looking once more for the init file
Init file not found! Attempting to prepare the WINEPREFIX
Using wine from Proton at path: '/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-7/files/bin'
Dereferencing '/home/deck/.local/share/Steam/steamapps/compatdata/2230110/pfx/drive_c/windows'
Running dependencies installation. This could take a while...
Winetricks not found...
Downloading latest winetricks...
Using winetricks 20240105-next - sha256sum: 5018f613bcb78df9b82296ebab621c03a9282c00140ffabd3a57c06efa9b309d with wine-9.0 (Staging) and WINEARCH=win64
sourcehansans already installed, skipping
sourcehansans already installed, skipping
vkd3d-proton-2.13/
vkd3d-proton-2.13/x64/
vkd3d-proton-2.13/x64/d3d12core.dll
vkd3d-proton-2.13/x64/d3d12.dll
vkd3d-proton-2.13/x86/
vkd3d-proton-2.13/x86/d3d12core.dll
vkd3d-proton-2.13/x86/d3d12.dll
vkd3d-proton-2.13/setup_vkd3d_proton.sh
Using native override for following DLLs: d3d12 d3d12core
Using native override for following DLLs: dxgi d3d9 d3d10core d3d11

**Comment by KingMiyo** [comment]
Never mind, took a lot of trying and trying and trying until stuff finally worked under 9.1.
Closing to save the modder a headache.

**Comment by marvin1099** [comment]
As smal info building is not working on some systems, if you have any more problems in the future you can use the download option instead of building if you are asked for it
