### ISSUE TITLE
Game fails to start with launch options

### ISSUE THREAD

**Issue by 6sicks6** [DaniAsh551/wemod-launcher#88]
Hello, thank you for all your hard work. I have followed your guides for wemod-launcher to the letter. When I get to the step to launch the game with the %command% launch option, the game the game thinks about starting then stops. I have deleted the prefix and retried MANY times. Any assistance would be much appreciated

**Comment by marvin1099** [comment]
First make shure the game runns without the wemod-launcher after that add `/home/$USER/wemod-launcher/wemod %command%` as it say in the guide then send over the `/home/$USER/wemod-launcher/wemod.log` file, if that file i missing say so but, since you sayed the game wants to start that file probably existists.

**Comment by 6sicks6** [comment]
The game runs just fine if i delete the launch options. I copy/pasted the launch options from the discord guide just in case i was typing it wrong. Wemod.log does not generate.

**Comment by marvin1099** [comment]
I will need the console output then,
for this make shure steam is closed, open a console, type steam, hit enter, start the game that has the wemod-launcher, finaly copy the steam console output and paste it here

**Comment by marvin1099** [comment]
Also you have executed  
`sudo chmod -R ug+x /home/$USER/wemod-launcher`  
as it sayed in the guide, its a comon mistake.

**Comment by 6sicks6** [comment]
I had tried it with and without the chmod string. This time with it, it worked. Got all the way through and verified mods work. Thank you for helping me, I really appreciate it.

**Comment by marvin1099** [comment]
No prob
