### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by mlgfx** [DaniAsh551/wemod-launcher#89]
I followed this guide and it seemed to installed WeMod correctly but after opening it again it says:
"Game closed to fast, Game detection may have failed."

And it gives me 3 options, to retry, to reinstall WeMod and other information which lead me to a FAQ "Why was WeMod flagged by my antivirus?"

EDIT:
I read through the closed issues and tried to use some tips from there. I installed the latest GE-Proton, deleted the prefix folder and tried to follow the guide from the start again but now I can't even seem to install it and just get a very long log file

**Comment by mlgfx** [comment]
This is the log file I get
[wemodlog.txt](https://github.com/user-attachments/files/16073715/wemodlog.txt)

**Comment by AlexSmith268** [comment]
I have the same issue. Here is my log file in the event it helps.
[wemod.log](https://github.com/user-attachments/files/16073996/wemod.log)

**Comment by marvin1099** [comment]
@mlgfx It seems there is some exaction error, i will look into this soon, for now run:
```
chmod -R 777 /home/deck/.local/share/Steam/steamapps/compatdata
```

@AlexSmith268 you have a other problem make sure you have python-pip installed it seems this may be the problem

**Comment by mlgfx** [comment]
It still didn't work
[wemod.log](https://github.com/user-attachments/files/16091127/wemod.log)

**Comment by marvin1099** [comment]
> It still didn't work [wemod.log](https://github.com/user-attachments/files/16091127/wemod.log)

Make sure you have tk installed and i pushed a update try to rerun it should update and work hopefully

**Comment by mlgfx** [comment]
How do I install TK? It's not showing up on the Discover store

**Comment by marvin1099** [comment]
Glad that it works now
