### ISSUE TITLE
Launching WeMod, Not Launching Game

### ISSUE THREAD

**Issue by seajaysec** [DaniAsh551/wemod-launcher#9]
Hi, after step 4.9 I believe there's a section missing in the instructions. At that step we have Steam launching WeMod, but WeMod can't operate on the game unless it's run through Steam... which Steam isn't able to do because instead of launching the game it's launching WeMod. How are we supposed to launch both?

**Comment by DaniAsh551** [comment]
I believe you misunderstood. The wemod-launcher is supposed to launch both the game and WeMod for you.

If you want some guidance, it may be easier to ask for it in the WeMod official discord.

You can join the discord server here: https://discord.gg/pM4Zfyn8

**Comment by DaniAsh551** [comment]
> Interesting, it's not launching the game alongside WeMod. Will join your discord and then comment back here whether or not a fix is discovered so the resolution is public info.

That would be ideal. Thank you
