### ISSUE TITLE
wemod cannot find hidden files.

### ISSUE THREAD

**Issue by ef2sz** [DaniAsh551/wemod-launcher#90]
wemod cannot find the .exe file because it is behind .local, a hidden file. I have wine set to "see dot files" but wemod refuses to see them. Can you enable "see mod files" on wemod's end in the code? Or if there's any other way to circumvent this?

I am using Garuda XFCE
The installation of steam and steam games go through .local
I have tried isolating the game from the steam installation folder but that does not work. I believe it would work if done the standard way, only if wemod was able to detect the game files in the first place.

**Comment by marvin1099** [comment]
You should be able to type the `.local` folder into the filebox.
even if the file cant be seen it can still be accessed if just  useing `.local` is not working try the full path to .local
it looks like this `/home/$USER/.local` but $USER will be username.

**Comment by marvin1099** [comment]
@ef2sz please report if this solved your issue.

**Comment by ef2sz** [comment]
Works now but I reinstalled the program and tried it on another game. I was not able to verify if this exact fix works or not. Thank you

**Comment by marvin1099** [comment]
Great
