### ISSUE TITLE
Followed guide, but cannot run game due to missing FreeSimpleGUI

### ISSUE THREAD

**Issue by PrinceOfPomp** [DaniAsh551/wemod-launcher#92]
I followed all the steps in the full guide, and currently have 

/home/REDACTED/wemod-launcher/wemod %command%

plugged into the launch options. However, when I go to launch the game, the process does not proceed to the next phase (the "build a new ID" portion) but instead produces the following log.

The script wemod-laucher is running on version 1.141
Package 'FreeSimpleGUI' is missing
Pip not installed. Using local pip.pyz
Package 'FreeSimpleGUI' is missing
Virtual environment created successfully.
Pip not installed. Using local pip.pyz
CRITICAL: Dependencies can't be installed
Failed to install dependencies. Error.
Do you want to open the log for more info on the exit error?

I'm currently on Linux Mint Cinnamon Edge 21.3

**Comment by ef2sz** [comment]
I was JUST going to post this exact issue after my last issue. Not even able to test the solution to my last issue due to this.

**Comment by marvin1099** [comment]
This is running a old version.
please rerun to update.
if it still says 1.141 and not 1.142 (or newer) you need to manually update.
For that run:
```
cd /home/$USER/wemod-launcher
git reset --hard origin
git pull
sudo chmod -R ug+x .
```

**Comment by marvin1099** [comment]
@ef2sz please report if this solved your issue.

**Comment by marvin1099** [comment]
@PrinceOfPomp please report if this solved your issue.

**Comment by PrinceOfPomp** [comment]
> @PrinceOfPomp please report if this solved your issue.

Just getting back to checking now. Will close if it works.

**Comment by PrinceOfPomp** [comment]
Yeah, no. It installed the prefix, before only pulling up the troubleshooter at launch, and now the game won't launch at all

**Comment by marvin1099** [comment]
I'm going to need the wemod.log file, please upload it here.
If this file is missing will need to do it a other way, but see if it is there.

**Comment by PrinceOfPomp** [comment]
> I'm going to need the currend wemod.log file, please upload it here. If this file is missing will need to do it a other way, but see if it is there.

Never mind, it worked after restarting my system

**Comment by marvin1099** [comment]
Great
