### ISSUE TITLE
Issue with WeMod launcher opening on steam deck but not game 

### ISSUE THREAD

**Issue by Vinn101** [DaniAsh551/wemod-launcher#95]
Hogwarts legacy was used. Attached is an explanation of the issue and the log from wemod. 
![IMG_6652](https://github.com/DaniAsh551/wemod-launcher/assets/13715340/4c93d101-af5d-48f9-b10d-e5d547c1f6a3)
[wemod.log](https://github.com/user-attachments/files/16113126/wemod.log)

**Comment by marvin1099** [comment]
As far as i can see in the log you are using a very old version of the wemod-laucher update by running:
```
cd /home/$USER/wemod-launcher
git reset --hard origin
git pull
sudo chmod -R ug+x .
```
