### ISSUE TITLE
[Bug] The wemod laucher fails with error infinte rerun

### ISSUE THREAD

**Issue by BouncyRocket** [DaniAsh551/wemod-launcher#99]
- OS: [e.g. SteamOS, Ubuntu]

**Comment by BouncyRocket** [comment]
![image](https://github.com/DaniAsh551/wemod-launcher/assets/88142470/892e4d72-ae57-4246-8e1c-0f62b3d44e58)

**Comment by marvin1099** [comment]
Try now, i think i made it work.

**Comment by marvin1099** [comment]
@BouncyRocket please report back if it works.

**Comment by BouncyRocket** [comment]
oki will

**Comment by BouncyRocket** [comment]
the game started but nothing appeared

**Comment by BouncyRocket** [comment]
it works! thanks.

**Comment by BouncyRocket** [comment]
but i found another error
local variable 'resp' referenced before assignment

**Comment by marvin1099** [comment]
Please send the log file in that case.

**Comment by marvin1099** [comment]
@BouncyRocket please send over the log file,
if the if the issue is still there,
i may have fixed it,
the script should automatically run on version 1.477.

**Comment by BouncyRocket** [comment]
Sorry for the late response I had fixed it by just deleting the Wemod folder and launcher and it reinstalled and works

**Comment by marvin1099** [comment]
Nice
